// This file was auto-generated by Fern from our API Definition.
export var CreateCreditNoteInput;
(function (CreateCreditNoteInput) {
    /** How the credit should be applied */
    CreateCreditNoteInput.CreditMethod = {
        RefundToPaymentMethod: "refund_to_payment_method",
        CustomerBalance: "customer_balance",
        External: "external",
    };
    /** Standardized reason code */
    CreateCreditNoteInput.ReasonCode = {
        CustomerRequest: "customer_request",
        DuplicateCharge: "duplicate_charge",
        ServiceIssue: "service_issue",
        BillingError: "billing_error",
        SubscriptionCancellation: "subscription_cancellation",
        Proration: "proration",
        Other: "other",
    };
})(CreateCreditNoteInput || (CreateCreditNoteInput = {}));
//# sourceMappingURL=CreateCreditNoteInput.js.map