// This file was auto-generated by Fern from our API Definition.
export var CancelSubscriptionInput;
(function (CancelSubscriptionInput) {
    /** Cancel mode: "immediately" revokes access now, "period_end" schedules cancellation at billing period end */
    CancelSubscriptionInput.Mode = {
        Immediately: "immediately",
        PeriodEnd: "period_end",
    };
})(CancelSubscriptionInput || (CancelSubscriptionInput = {}));
//# sourceMappingURL=CancelSubscriptionInput.js.map