// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         subscriptionId: "subscriptionId",
 *         currency: "USD",
 *         unit_amount_minor: 2999
 *     }
 */
export interface CreateSubscriptionItemInput {
    /** Subscription UUID */
    subscriptionId: string;
    /** Product UUID to link to this item */
    product_id?: string;
    /** Price UUID to link to this item */
    price_id?: string;
    /** Item description */
    description?: string;
    /** Item quantity */
    quantity?: number;
    /** ISO 4217 currency code */
    currency: string;
    /** Unit price in cents */
    unit_amount_minor: number;
    /** Determines if orders are created on renewal */
    fulfillment_type?: CreateSubscriptionItemInput.FulfillmentType;
    /** Custom key-value metadata */
    metadata?: Record<string, unknown>;
}

export namespace CreateSubscriptionItemInput {
    /** Determines if orders are created on renewal */
    export const FulfillmentType = {
        None: "none",
        Physical: "physical",
        Digital: "digital",
    } as const;
    export type FulfillmentType = (typeof FulfillmentType)[keyof typeof FulfillmentType];
}
