// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         newQuantity: 1
 *     }
 */
export interface SubscriptionsChangeQuantityRequest {
    /** Subscription UUID */
    id: string;
    newQuantity: number;
    prorationBehavior?: SubscriptionsChangeQuantityRequest.ProrationBehavior;
    effectiveDate?: string;
    reason?: string;
}

export namespace SubscriptionsChangeQuantityRequest {
    export const ProrationBehavior = {
        InvoiceImmediately: "invoice_immediately",
        NextInvoice: "next_invoice",
        None: "none",
    } as const;
    export type ProrationBehavior = (typeof ProrationBehavior)[keyof typeof ProrationBehavior];
}
