// This file was auto-generated by Fern from our API Definition.
export var SubscriptionsCreateRequest;
(function (SubscriptionsCreateRequest) {
    SubscriptionsCreateRequest.BillingEndStrategy = {
        Indefinite: "indefinite",
        OnDate: "on_date",
        AfterCycles: "after_cycles",
    };
    SubscriptionsCreateRequest.ProrationMode = {
        Immediate: "immediate",
        NextInvoice: "next_invoice",
        None: "none",
    };
})(SubscriptionsCreateRequest || (SubscriptionsCreateRequest = {}));
//# sourceMappingURL=SubscriptionsCreateRequest.js.map