// This file was auto-generated by Fern from our API Definition.
export var SubscriptionsUpdateRequest;
(function (SubscriptionsUpdateRequest) {
    SubscriptionsUpdateRequest.Status = {
        Trialing: "trialing",
        Active: "active",
        PastDue: "past_due",
        Paused: "paused",
        Canceled: "canceled",
        Expired: "expired",
    };
})(SubscriptionsUpdateRequest || (SubscriptionsUpdateRequest = {}));
//# sourceMappingURL=SubscriptionsUpdateRequest.js.map