// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         subscriptionId: "subscriptionId",
 *         itemId: "itemId"
 *     }
 */
export interface UpdateSubscriptionItemInput {
    /** Subscription UUID */
    subscriptionId: string;
    /** Item UUID */
    itemId: string;
    /** Item quantity */
    quantity?: number;
    /** Item description */
    description?: string;
    /** Unit price in cents */
    unit_amount_minor?: number;
    /** Determines if orders are created on renewal */
    fulfillment_type?: UpdateSubscriptionItemInput.FulfillmentType;
    /** Custom key-value metadata */
    metadata?: Record<string, unknown>;
}

export namespace UpdateSubscriptionItemInput {
    /** Determines if orders are created on renewal */
    export const FulfillmentType = {
        None: "none",
        Physical: "physical",
        Digital: "digital",
    } as const;
    export type FulfillmentType = (typeof FulfillmentType)[keyof typeof FulfillmentType];
}
