import { AnalyticsClient } from "./api/resources/analytics/client/Client.js";
import { AppsClient } from "./api/resources/apps/client/Client.js";
import { BillingClient } from "./api/resources/billing/client/Client.js";
import { BusinessesClient } from "./api/resources/businesses/client/Client.js";
import { ChargesClient } from "./api/resources/charges/client/Client.js";
import { CheckoutSessionsClient } from "./api/resources/checkoutSessions/client/Client.js";
import { ClientsClient } from "./api/resources/clients/client/Client.js";
import { CommsClient } from "./api/resources/comms/client/Client.js";
import { CreditNotesClient } from "./api/resources/creditNotes/client/Client.js";
import { CustomersClient } from "./api/resources/customers/client/Client.js";
import { DiscountsClient } from "./api/resources/discounts/client/Client.js";
import { DisputesClient } from "./api/resources/disputes/client/Client.js";
import { EntitlementsClient } from "./api/resources/entitlements/client/Client.js";
import { EventsClient } from "./api/resources/events/client/Client.js";
import { FinanceClient } from "./api/resources/finance/client/Client.js";
import { IntegrationsClient } from "./api/resources/integrations/client/Client.js";
import { InvoicesClient } from "./api/resources/invoices/client/Client.js";
import { OrdersClient } from "./api/resources/orders/client/Client.js";
import { PaymentAttemptsClient } from "./api/resources/paymentAttempts/client/Client.js";
import { PaymentIntentsClient } from "./api/resources/paymentIntents/client/Client.js";
import { PaymentLinksClient } from "./api/resources/paymentLinks/client/Client.js";
import { PaymentMethodsClient } from "./api/resources/paymentMethods/client/Client.js";
import { PaymentsClient } from "./api/resources/payments/client/Client.js";
import { PayoutsClient } from "./api/resources/payouts/client/Client.js";
import { PricesClient } from "./api/resources/prices/client/Client.js";
import { ProductsClient } from "./api/resources/products/client/Client.js";
import { RefundsClient } from "./api/resources/refunds/client/Client.js";
import { SetupIntentsClient } from "./api/resources/setupIntents/client/Client.js";
import { SubscriptionSchedulesClient } from "./api/resources/subscriptionSchedules/client/Client.js";
import { SubscriptionsClient } from "./api/resources/subscriptions/client/Client.js";
import { SyncStateClient } from "./api/resources/syncState/client/Client.js";
import { TaxRatesClient } from "./api/resources/taxRates/client/Client.js";
import { TerminalDevicesClient } from "./api/resources/terminalDevices/client/Client.js";
import { TerminalPaymentsClient } from "./api/resources/terminalPayments/client/Client.js";
import { UserInvitationsClient } from "./api/resources/userInvitations/client/Client.js";
import { VoidsClient } from "./api/resources/voids/client/Client.js";
import { WebhookEndpointsClient } from "./api/resources/webhookEndpoints/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth } from "./BaseClient.js";
export declare namespace RevKeenClient {
    type Options = BaseClientOptions;
    interface RequestOptions extends BaseRequestOptions {
    }
}
export declare class RevKeenClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<RevKeenClient.Options>;
    protected _invoices: InvoicesClient | undefined;
    protected _userInvitations: UserInvitationsClient | undefined;
    protected _products: ProductsClient | undefined;
    protected _apps: AppsClient | undefined;
    protected _checkoutSessions: CheckoutSessionsClient | undefined;
    protected _businesses: BusinessesClient | undefined;
    protected _clients: ClientsClient | undefined;
    protected _entitlements: EntitlementsClient | undefined;
    protected _customers: CustomersClient | undefined;
    protected _subscriptions: SubscriptionsClient | undefined;
    protected _comms: CommsClient | undefined;
    protected _analytics: AnalyticsClient | undefined;
    protected _finance: FinanceClient | undefined;
    protected _payouts: PayoutsClient | undefined;
    protected _refunds: RefundsClient | undefined;
    protected _voids: VoidsClient | undefined;
    protected _creditNotes: CreditNotesClient | undefined;
    protected _disputes: DisputesClient | undefined;
    protected _discounts: DiscountsClient | undefined;
    protected _paymentLinks: PaymentLinksClient | undefined;
    protected _paymentAttempts: PaymentAttemptsClient | undefined;
    protected _charges: ChargesClient | undefined;
    protected _billing: BillingClient | undefined;
    protected _prices: PricesClient | undefined;
    protected _taxRates: TaxRatesClient | undefined;
    protected _orders: OrdersClient | undefined;
    protected _payments: PaymentsClient | undefined;
    protected _integrations: IntegrationsClient | undefined;
    protected _syncState: SyncStateClient | undefined;
    protected _webhookEndpoints: WebhookEndpointsClient | undefined;
    protected _paymentIntents: PaymentIntentsClient | undefined;
    protected _setupIntents: SetupIntentsClient | undefined;
    protected _paymentMethods: PaymentMethodsClient | undefined;
    protected _events: EventsClient | undefined;
    protected _subscriptionSchedules: SubscriptionSchedulesClient | undefined;
    protected _terminalPayments: TerminalPaymentsClient | undefined;
    protected _terminalDevices: TerminalDevicesClient | undefined;
    constructor(options: RevKeenClient.Options);
    get invoices(): InvoicesClient;
    get userInvitations(): UserInvitationsClient;
    get products(): ProductsClient;
    get apps(): AppsClient;
    get checkoutSessions(): CheckoutSessionsClient;
    get businesses(): BusinessesClient;
    get clients(): ClientsClient;
    get entitlements(): EntitlementsClient;
    get customers(): CustomersClient;
    get subscriptions(): SubscriptionsClient;
    get comms(): CommsClient;
    get analytics(): AnalyticsClient;
    get finance(): FinanceClient;
    get payouts(): PayoutsClient;
    get refunds(): RefundsClient;
    get voids(): VoidsClient;
    get creditNotes(): CreditNotesClient;
    get disputes(): DisputesClient;
    get discounts(): DiscountsClient;
    get paymentLinks(): PaymentLinksClient;
    get paymentAttempts(): PaymentAttemptsClient;
    get charges(): ChargesClient;
    get billing(): BillingClient;
    get prices(): PricesClient;
    get taxRates(): TaxRatesClient;
    get orders(): OrdersClient;
    get payments(): PaymentsClient;
    get integrations(): IntegrationsClient;
    get syncState(): SyncStateClient;
    get webhookEndpoints(): WebhookEndpointsClient;
    get paymentIntents(): PaymentIntentsClient;
    get setupIntents(): SetupIntentsClient;
    get paymentMethods(): PaymentMethodsClient;
    get events(): EventsClient;
    get subscriptionSchedules(): SubscriptionSchedulesClient;
    get terminalPayments(): TerminalPaymentsClient;
    get terminalDevices(): TerminalDevicesClient;
}
//# sourceMappingURL=Client.d.ts.map