// This file was auto-generated by Fern from our API Definition.
import { AnalyticsClient } from "./api/resources/analytics/client/Client.js";
import { AppsClient } from "./api/resources/apps/client/Client.js";
import { BillingClient } from "./api/resources/billing/client/Client.js";
import { BusinessesClient } from "./api/resources/businesses/client/Client.js";
import { ChargesClient } from "./api/resources/charges/client/Client.js";
import { CheckoutSessionsClient } from "./api/resources/checkoutSessions/client/Client.js";
import { ClientsClient } from "./api/resources/clients/client/Client.js";
import { CommsClient } from "./api/resources/comms/client/Client.js";
import { CreditNotesClient } from "./api/resources/creditNotes/client/Client.js";
import { CustomersClient } from "./api/resources/customers/client/Client.js";
import { DiscountsClient } from "./api/resources/discounts/client/Client.js";
import { DisputesClient } from "./api/resources/disputes/client/Client.js";
import { EntitlementsClient } from "./api/resources/entitlements/client/Client.js";
import { EventsClient } from "./api/resources/events/client/Client.js";
import { FinanceClient } from "./api/resources/finance/client/Client.js";
import { IntegrationsClient } from "./api/resources/integrations/client/Client.js";
import { InvoicesClient } from "./api/resources/invoices/client/Client.js";
import { OrdersClient } from "./api/resources/orders/client/Client.js";
import { PaymentAttemptsClient } from "./api/resources/paymentAttempts/client/Client.js";
import { PaymentIntentsClient } from "./api/resources/paymentIntents/client/Client.js";
import { PaymentLinksClient } from "./api/resources/paymentLinks/client/Client.js";
import { PaymentMethodsClient } from "./api/resources/paymentMethods/client/Client.js";
import { PaymentsClient } from "./api/resources/payments/client/Client.js";
import { PayoutsClient } from "./api/resources/payouts/client/Client.js";
import { PricesClient } from "./api/resources/prices/client/Client.js";
import { ProductsClient } from "./api/resources/products/client/Client.js";
import { RefundsClient } from "./api/resources/refunds/client/Client.js";
import { SetupIntentsClient } from "./api/resources/setupIntents/client/Client.js";
import { SubscriptionSchedulesClient } from "./api/resources/subscriptionSchedules/client/Client.js";
import { SubscriptionsClient } from "./api/resources/subscriptions/client/Client.js";
import { SyncStateClient } from "./api/resources/syncState/client/Client.js";
import { TaxRatesClient } from "./api/resources/taxRates/client/Client.js";
import { TerminalDevicesClient } from "./api/resources/terminalDevices/client/Client.js";
import { TerminalPaymentsClient } from "./api/resources/terminalPayments/client/Client.js";
import { UserInvitationsClient } from "./api/resources/userInvitations/client/Client.js";
import { VoidsClient } from "./api/resources/voids/client/Client.js";
import { WebhookEndpointsClient } from "./api/resources/webhookEndpoints/client/Client.js";
import { normalizeClientOptionsWithAuth } from "./BaseClient.js";
export class RevKeenClient {
    constructor(options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }
    get invoices() {
        return (this._invoices ?? (this._invoices = new InvoicesClient(this._options)));
    }
    get userInvitations() {
        return (this._userInvitations ?? (this._userInvitations = new UserInvitationsClient(this._options)));
    }
    get products() {
        return (this._products ?? (this._products = new ProductsClient(this._options)));
    }
    get apps() {
        return (this._apps ?? (this._apps = new AppsClient(this._options)));
    }
    get checkoutSessions() {
        return (this._checkoutSessions ?? (this._checkoutSessions = new CheckoutSessionsClient(this._options)));
    }
    get businesses() {
        return (this._businesses ?? (this._businesses = new BusinessesClient(this._options)));
    }
    get clients() {
        return (this._clients ?? (this._clients = new ClientsClient(this._options)));
    }
    get entitlements() {
        return (this._entitlements ?? (this._entitlements = new EntitlementsClient(this._options)));
    }
    get customers() {
        return (this._customers ?? (this._customers = new CustomersClient(this._options)));
    }
    get subscriptions() {
        return (this._subscriptions ?? (this._subscriptions = new SubscriptionsClient(this._options)));
    }
    get comms() {
        return (this._comms ?? (this._comms = new CommsClient(this._options)));
    }
    get analytics() {
        return (this._analytics ?? (this._analytics = new AnalyticsClient(this._options)));
    }
    get finance() {
        return (this._finance ?? (this._finance = new FinanceClient(this._options)));
    }
    get payouts() {
        return (this._payouts ?? (this._payouts = new PayoutsClient(this._options)));
    }
    get refunds() {
        return (this._refunds ?? (this._refunds = new RefundsClient(this._options)));
    }
    get voids() {
        return (this._voids ?? (this._voids = new VoidsClient(this._options)));
    }
    get creditNotes() {
        return (this._creditNotes ?? (this._creditNotes = new CreditNotesClient(this._options)));
    }
    get disputes() {
        return (this._disputes ?? (this._disputes = new DisputesClient(this._options)));
    }
    get discounts() {
        return (this._discounts ?? (this._discounts = new DiscountsClient(this._options)));
    }
    get paymentLinks() {
        return (this._paymentLinks ?? (this._paymentLinks = new PaymentLinksClient(this._options)));
    }
    get paymentAttempts() {
        return (this._paymentAttempts ?? (this._paymentAttempts = new PaymentAttemptsClient(this._options)));
    }
    get charges() {
        return (this._charges ?? (this._charges = new ChargesClient(this._options)));
    }
    get billing() {
        return (this._billing ?? (this._billing = new BillingClient(this._options)));
    }
    get prices() {
        return (this._prices ?? (this._prices = new PricesClient(this._options)));
    }
    get taxRates() {
        return (this._taxRates ?? (this._taxRates = new TaxRatesClient(this._options)));
    }
    get orders() {
        return (this._orders ?? (this._orders = new OrdersClient(this._options)));
    }
    get payments() {
        return (this._payments ?? (this._payments = new PaymentsClient(this._options)));
    }
    get integrations() {
        return (this._integrations ?? (this._integrations = new IntegrationsClient(this._options)));
    }
    get syncState() {
        return (this._syncState ?? (this._syncState = new SyncStateClient(this._options)));
    }
    get webhookEndpoints() {
        return (this._webhookEndpoints ?? (this._webhookEndpoints = new WebhookEndpointsClient(this._options)));
    }
    get paymentIntents() {
        return (this._paymentIntents ?? (this._paymentIntents = new PaymentIntentsClient(this._options)));
    }
    get setupIntents() {
        return (this._setupIntents ?? (this._setupIntents = new SetupIntentsClient(this._options)));
    }
    get paymentMethods() {
        return (this._paymentMethods ?? (this._paymentMethods = new PaymentMethodsClient(this._options)));
    }
    get events() {
        return (this._events ?? (this._events = new EventsClient(this._options)));
    }
    get subscriptionSchedules() {
        return (this._subscriptionSchedules ?? (this._subscriptionSchedules = new SubscriptionSchedulesClient(this._options)));
    }
    get terminalPayments() {
        return (this._terminalPayments ?? (this._terminalPayments = new TerminalPaymentsClient(this._options)));
    }
    get terminalDevices() {
        return (this._terminalDevices ?? (this._terminalDevices = new TerminalDevicesClient(this._options)));
    }
}
//# sourceMappingURL=Client.js.map