// This file was auto-generated by Fern from our API Definition.

import { AnalyticsClient } from "./api/resources/analytics/client/Client.js";
import { AppsClient } from "./api/resources/apps/client/Client.js";
import { BillingClient } from "./api/resources/billing/client/Client.js";
import { BusinessesClient } from "./api/resources/businesses/client/Client.js";
import { ChargesClient } from "./api/resources/charges/client/Client.js";
import { CheckoutSessionsClient } from "./api/resources/checkoutSessions/client/Client.js";
import { ClientsClient } from "./api/resources/clients/client/Client.js";
import { CommsClient } from "./api/resources/comms/client/Client.js";
import { CreditNotesClient } from "./api/resources/creditNotes/client/Client.js";
import { CustomersClient } from "./api/resources/customers/client/Client.js";
import { DiscountsClient } from "./api/resources/discounts/client/Client.js";
import { DisputesClient } from "./api/resources/disputes/client/Client.js";
import { EntitlementsClient } from "./api/resources/entitlements/client/Client.js";
import { EventsClient } from "./api/resources/events/client/Client.js";
import { FinanceClient } from "./api/resources/finance/client/Client.js";
import { IntegrationsClient } from "./api/resources/integrations/client/Client.js";
import { InvoicesClient } from "./api/resources/invoices/client/Client.js";
import { MetersClient } from "./api/resources/meters/client/Client.js";
import { OrdersClient } from "./api/resources/orders/client/Client.js";
import { PaymentAttemptsClient } from "./api/resources/paymentAttempts/client/Client.js";
import { PaymentIntentsClient } from "./api/resources/paymentIntents/client/Client.js";
import { PaymentLinksClient } from "./api/resources/paymentLinks/client/Client.js";
import { PaymentMethodsClient } from "./api/resources/paymentMethods/client/Client.js";
import { PaymentsClient } from "./api/resources/payments/client/Client.js";
import { PayoutsClient } from "./api/resources/payouts/client/Client.js";
import { PricesClient } from "./api/resources/prices/client/Client.js";
import { ProductsClient } from "./api/resources/products/client/Client.js";
import { RefundsClient } from "./api/resources/refunds/client/Client.js";
import { SetupIntentsClient } from "./api/resources/setupIntents/client/Client.js";
import { SubscriptionSchedulesClient } from "./api/resources/subscriptionSchedules/client/Client.js";
import { SubscriptionsClient } from "./api/resources/subscriptions/client/Client.js";
import { SyncStateClient } from "./api/resources/syncState/client/Client.js";
import { TaxRatesClient } from "./api/resources/taxRates/client/Client.js";
import { TerminalDevicesClient } from "./api/resources/terminalDevices/client/Client.js";
import { TerminalPaymentsClient } from "./api/resources/terminalPayments/client/Client.js";
import { UsageClient } from "./api/resources/usage/client/Client.js";
import { UserInvitationsClient } from "./api/resources/userInvitations/client/Client.js";
import { VoidsClient } from "./api/resources/voids/client/Client.js";
import { WebhookEndpointsClient } from "./api/resources/webhookEndpoints/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace RevKeenClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class RevKeenClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<RevKeenClient.Options>;
    protected _invoices: InvoicesClient | undefined;
    protected _userInvitations: UserInvitationsClient | undefined;
    protected _products: ProductsClient | undefined;
    protected _apps: AppsClient | undefined;
    protected _checkoutSessions: CheckoutSessionsClient | undefined;
    protected _businesses: BusinessesClient | undefined;
    protected _clients: ClientsClient | undefined;
    protected _entitlements: EntitlementsClient | undefined;
    protected _customers: CustomersClient | undefined;
    protected _subscriptions: SubscriptionsClient | undefined;
    protected _comms: CommsClient | undefined;
    protected _analytics: AnalyticsClient | undefined;
    protected _finance: FinanceClient | undefined;
    protected _payouts: PayoutsClient | undefined;
    protected _refunds: RefundsClient | undefined;
    protected _voids: VoidsClient | undefined;
    protected _creditNotes: CreditNotesClient | undefined;
    protected _disputes: DisputesClient | undefined;
    protected _discounts: DiscountsClient | undefined;
    protected _paymentLinks: PaymentLinksClient | undefined;
    protected _paymentAttempts: PaymentAttemptsClient | undefined;
    protected _charges: ChargesClient | undefined;
    protected _billing: BillingClient | undefined;
    protected _prices: PricesClient | undefined;
    protected _meters: MetersClient | undefined;
    protected _taxRates: TaxRatesClient | undefined;
    protected _orders: OrdersClient | undefined;
    protected _payments: PaymentsClient | undefined;
    protected _integrations: IntegrationsClient | undefined;
    protected _syncState: SyncStateClient | undefined;
    protected _webhookEndpoints: WebhookEndpointsClient | undefined;
    protected _paymentIntents: PaymentIntentsClient | undefined;
    protected _setupIntents: SetupIntentsClient | undefined;
    protected _paymentMethods: PaymentMethodsClient | undefined;
    protected _events: EventsClient | undefined;
    protected _subscriptionSchedules: SubscriptionSchedulesClient | undefined;
    protected _terminalPayments: TerminalPaymentsClient | undefined;
    protected _terminalDevices: TerminalDevicesClient | undefined;
    protected _usage: UsageClient | undefined;

    constructor(options: RevKeenClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get invoices(): InvoicesClient {
        return (this._invoices ??= new InvoicesClient(this._options));
    }

    public get userInvitations(): UserInvitationsClient {
        return (this._userInvitations ??= new UserInvitationsClient(this._options));
    }

    public get products(): ProductsClient {
        return (this._products ??= new ProductsClient(this._options));
    }

    public get apps(): AppsClient {
        return (this._apps ??= new AppsClient(this._options));
    }

    public get checkoutSessions(): CheckoutSessionsClient {
        return (this._checkoutSessions ??= new CheckoutSessionsClient(this._options));
    }

    public get businesses(): BusinessesClient {
        return (this._businesses ??= new BusinessesClient(this._options));
    }

    public get clients(): ClientsClient {
        return (this._clients ??= new ClientsClient(this._options));
    }

    public get entitlements(): EntitlementsClient {
        return (this._entitlements ??= new EntitlementsClient(this._options));
    }

    public get customers(): CustomersClient {
        return (this._customers ??= new CustomersClient(this._options));
    }

    public get subscriptions(): SubscriptionsClient {
        return (this._subscriptions ??= new SubscriptionsClient(this._options));
    }

    public get comms(): CommsClient {
        return (this._comms ??= new CommsClient(this._options));
    }

    public get analytics(): AnalyticsClient {
        return (this._analytics ??= new AnalyticsClient(this._options));
    }

    public get finance(): FinanceClient {
        return (this._finance ??= new FinanceClient(this._options));
    }

    public get payouts(): PayoutsClient {
        return (this._payouts ??= new PayoutsClient(this._options));
    }

    public get refunds(): RefundsClient {
        return (this._refunds ??= new RefundsClient(this._options));
    }

    public get voids(): VoidsClient {
        return (this._voids ??= new VoidsClient(this._options));
    }

    public get creditNotes(): CreditNotesClient {
        return (this._creditNotes ??= new CreditNotesClient(this._options));
    }

    public get disputes(): DisputesClient {
        return (this._disputes ??= new DisputesClient(this._options));
    }

    public get discounts(): DiscountsClient {
        return (this._discounts ??= new DiscountsClient(this._options));
    }

    public get paymentLinks(): PaymentLinksClient {
        return (this._paymentLinks ??= new PaymentLinksClient(this._options));
    }

    public get paymentAttempts(): PaymentAttemptsClient {
        return (this._paymentAttempts ??= new PaymentAttemptsClient(this._options));
    }

    public get charges(): ChargesClient {
        return (this._charges ??= new ChargesClient(this._options));
    }

    public get billing(): BillingClient {
        return (this._billing ??= new BillingClient(this._options));
    }

    public get prices(): PricesClient {
        return (this._prices ??= new PricesClient(this._options));
    }

    public get meters(): MetersClient {
        return (this._meters ??= new MetersClient(this._options));
    }

    public get taxRates(): TaxRatesClient {
        return (this._taxRates ??= new TaxRatesClient(this._options));
    }

    public get orders(): OrdersClient {
        return (this._orders ??= new OrdersClient(this._options));
    }

    public get payments(): PaymentsClient {
        return (this._payments ??= new PaymentsClient(this._options));
    }

    public get integrations(): IntegrationsClient {
        return (this._integrations ??= new IntegrationsClient(this._options));
    }

    public get syncState(): SyncStateClient {
        return (this._syncState ??= new SyncStateClient(this._options));
    }

    public get webhookEndpoints(): WebhookEndpointsClient {
        return (this._webhookEndpoints ??= new WebhookEndpointsClient(this._options));
    }

    public get paymentIntents(): PaymentIntentsClient {
        return (this._paymentIntents ??= new PaymentIntentsClient(this._options));
    }

    public get setupIntents(): SetupIntentsClient {
        return (this._setupIntents ??= new SetupIntentsClient(this._options));
    }

    public get paymentMethods(): PaymentMethodsClient {
        return (this._paymentMethods ??= new PaymentMethodsClient(this._options));
    }

    public get events(): EventsClient {
        return (this._events ??= new EventsClient(this._options));
    }

    public get subscriptionSchedules(): SubscriptionSchedulesClient {
        return (this._subscriptionSchedules ??= new SubscriptionSchedulesClient(this._options));
    }

    public get terminalPayments(): TerminalPaymentsClient {
        return (this._terminalPayments ??= new TerminalPaymentsClient(this._options));
    }

    public get terminalDevices(): TerminalDevicesClient {
        return (this._terminalDevices ??= new TerminalDevicesClient(this._options));
    }

    public get usage(): UsageClient {
        return (this._usage ??= new UsageClient(this._options));
    }
}
