// This file was auto-generated by Fern from our API Definition.
export var BankAccountDetails;
(function (BankAccountDetails) {
    /** The type of bank account */
    BankAccountDetails.AccountType = {
        Checking: "checking",
        Savings: "savings",
    };
})(BankAccountDetails || (BankAccountDetails = {}));
//# sourceMappingURL=BankAccountDetails.js.map