// This file was auto-generated by Fern from our API Definition.

export interface BatchIngestResult {
    object: BatchIngestResult.Object_;
    summary: BatchIngestResult.Summary;
    data: BatchIngestResult.Data.Item[];
}

export namespace BatchIngestResult {
    export const Object_ = {
        UsageEventBatchResult: "usage_event_batch_result",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];

    export interface Summary {
        ingested: number;
        duplicate: number;
        skipped: number;
        failed: number;
    }

    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            index: number;
            status: Item.Status;
            id?: string;
            reason?: string;
        }

        export namespace Item {
            export const Status = {
                Ingested: "ingested",
                Duplicate: "duplicate",
                Skipped: "skipped",
                Failed: "failed",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }
}
