// This file was auto-generated by Fern from our API Definition.

export interface Benefit {
    id: string;
    name: string;
    description: string | null;
    benefitType: string;
    benefitKey: string;
    category: string | null;
    iconUrl: string | null;
    displayOrder: string | null;
    isActive: boolean | null;
    defaultValue?: unknown;
    config?: unknown;
}
