// This file was auto-generated by Fern from our API Definition.

/**
 * A preview of upcoming billing charges for a subscription, showing line items, amounts, and billing dates.
 */
export interface BillingPreviewResponse {
    data: BillingPreviewResponse.Data;
}

export namespace BillingPreviewResponse {
    export interface Data {
        items: Data.Items.Item[];
        summary: string;
        totalAmountMinor: number;
        firstChargeDate: string;
        trialEndDate: string | null;
        scheduleEndDate: string | null;
        timezone: string;
    }

    export namespace Data {
        export type Items = Items.Item[];

        export namespace Items {
            export interface Item {
                sequence: number;
                date: string;
                formattedDate: string;
                dayName: string;
                amountMinor: number;
                formattedAmount: string;
                isTrialEnd?: boolean;
                isFirstCharge?: boolean;
                isFinalPayment?: boolean;
            }
        }
    }
}
