// This file was auto-generated by Fern from our API Definition.

export interface BillingAnchorRulesResponse {
    data: BillingAnchorRulesResponse.Data.Item[];
}

export namespace BillingAnchorRulesResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            value: string;
            label: string;
            description: string;
            requiresAnchorDay: boolean;
        }
    }
}
