// This file was auto-generated by Fern from our API Definition.

/**
 * Card details (if type is 'card')
 */
export interface CardDetails {
    /** The card brand */
    brand: CardDetails.Brand | null;
    /** The last 4 digits of the card number */
    last4: string | null;
    /** Expiration month (1-12) */
    exp_month: number | null;
    /** Expiration year */
    exp_year: number | null;
    /** The card funding type */
    funding: CardDetails.Funding | null;
}

export namespace CardDetails {
    /** The card brand */
    export const Brand = {
        Visa: "visa",
        Mastercard: "mastercard",
        Amex: "amex",
        Discover: "discover",
        Diners: "diners",
        Jcb: "jcb",
        Unionpay: "unionpay",
        Unknown: "unknown",
    } as const;
    export type Brand = (typeof Brand)[keyof typeof Brand];
    /** The card funding type */
    export const Funding = {
        Credit: "credit",
        Debit: "debit",
        Prepaid: "prepaid",
        Unknown: "unknown",
    } as const;
    export type Funding = (typeof Funding)[keyof typeof Funding];
}
