// This file was auto-generated by Fern from our API Definition.
export var ChargeListResponse;
(function (ChargeListResponse) {
    let Data;
    (function (Data) {
        let Item;
        (function (Item) {
            Item.Status = {
                Pending: "pending",
                Processing: "processing",
                Succeeded: "succeeded",
                Failed: "failed",
                Refunded: "refunded",
                PartiallyRefunded: "partially_refunded",
                Voided: "voided",
            };
        })(Item = Data.Item || (Data.Item = {}));
    })(Data = ChargeListResponse.Data || (ChargeListResponse.Data = {}));
})(ChargeListResponse || (ChargeListResponse = {}));
//# sourceMappingURL=ChargeListResponse.js.map