// This file was auto-generated by Fern from our API Definition.
export var CheckoutSession;
(function (CheckoutSession) {
    CheckoutSession.Object_ = {
        CheckoutSession: "checkout_session",
    };
})(CheckoutSession || (CheckoutSession = {}));
//# sourceMappingURL=CheckoutSession.js.map