// This file was auto-generated by Fern from our API Definition.

export interface CheckoutSessionExpireResponse {
    data: CheckoutSessionExpireResponse.Data;
    requestId: string;
}

export namespace CheckoutSessionExpireResponse {
    export interface Data {
        id: string;
        status: Data.Status;
        expiredAt: string;
    }

    export namespace Data {
        export const Status = {
            Expired: "expired",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }
}
