// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

/**
 * A single credit note with full details including the associated invoice and refund.
 */
export interface CreditNoteRetrieveResponse {
    data: RevKeen.CreditNote;
}
