// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

/**
 * The credit note after being voided, reversing its accounting effect.
 */
export interface CreditNoteVoidResponse {
    data: RevKeen.CreditNote;
}
