// This file was auto-generated by Fern from our API Definition.

export interface CustomerRetrieveResponse {
    data: CustomerRetrieveResponse.Data;
}

export namespace CustomerRetrieveResponse {
    export interface Data {
        id: string;
        merchantId: string;
        merchantRefId?: string;
        email: string;
        name?: string;
        phone?: string;
        authUserId?: string;
        metadata?: Record<string, unknown>;
        /** Custom fields */
        customFields?: Record<string, unknown>;
        createdAt: string;
        updatedAt: string;
    }
}
