// This file was auto-generated by Fern from our API Definition.

export interface CustomerInvoice {
    id: string;
    customer_id: string;
    invoice_number: string | null;
    status: string;
    total_minor: number;
    currency: string;
    due_date: string | null;
    created_at: string;
    updated_at: string;
}
