// This file was auto-generated by Fern from our API Definition.
export var CvvCodeInterpretation;
(function (CvvCodeInterpretation) {
    /** Type of CVV match */
    CvvCodeInterpretation.MatchType = {
        Match: "match",
        NoMatch: "no_match",
        NotProcessed: "not_processed",
        NotProvided: "not_provided",
        IssuerNotCertified: "issuer_not_certified",
        Error: "error",
    };
    /** Risk level based on CVV result. low: match, medium: not processed, high: no match */
    CvvCodeInterpretation.RiskLevel = {
        Low: "low",
        Medium: "medium",
        High: "high",
        Unknown: "unknown",
    };
})(CvvCodeInterpretation || (CvvCodeInterpretation = {}));
//# sourceMappingURL=CvvCodeInterpretation.js.map