// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

/**
 * The newly created discount object.
 */
export interface DiscountCreateResponse {
    data: RevKeen.Discount;
}
