// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

/**
 * A paginated list of discounts matching the query filters.
 */
export interface DiscountListResponse {
    data: RevKeen.Discount[];
    meta: DiscountListResponse.Meta;
}

export namespace DiscountListResponse {
    export interface Meta {
        total: number;
        limit: number;
        offset: number;
        has_more: boolean;
    }
}
