// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

export interface EventListResponse {
    object: EventListResponse.Object_;
    data: RevKeen.Event[];
    has_more: boolean;
    /** The URL for accessing this list */
    url: string;
}

export namespace EventListResponse {
    export const Object_ = {
        List: "list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
