// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

/**
 * Export job status and details.
 */
export interface ExportRetrieveResponse {
    data: RevKeen.Export;
}
