// This file was auto-generated by Fern from our API Definition.
export var Invoice;
(function (Invoice) {
    let SubscriptionTerms;
    (function (SubscriptionTerms) {
        /** How to collect payment for recurring invoices */
        SubscriptionTerms.CollectionMethod = {
            ChargeAutomatically: "charge_automatically",
            SendInvoice: "send_invoice",
        };
        /** When the subscription billing cycle starts */
        SubscriptionTerms.StartMode = {
            WhenPaid: "when_paid",
            OnInvoiceDate: "on_invoice_date",
            FirstOfNextMonth: "first_of_next_month",
            SpecificDate: "specific_date",
        };
        /** How the subscription duration is determined */
        SubscriptionTerms.DurationType = {
            UntilCancelled: "until_cancelled",
            FixedCycles: "fixed_cycles",
            EndDate: "end_date",
        };
        /** Whether to charge the first cycle immediately or defer to the start date */
        SubscriptionTerms.FirstPaymentBehavior = {
            ChargeFirstCycleNow: "charge_first_cycle_now",
            DeferFirstCycleToStartDate: "defer_first_cycle_to_start_date",
        };
    })(SubscriptionTerms = Invoice.SubscriptionTerms || (Invoice.SubscriptionTerms = {}));
})(Invoice || (Invoice = {}));
//# sourceMappingURL=Invoice.js.map