// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

/**
 * A list of invoices matching the query filters.
 */
export interface InvoiceListResponse {
    data: RevKeen.Invoice[];
    requestId: string;
}
