// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

/**
 * A single invoice object with request tracking metadata.
 */
export interface InvoiceResponse {
    data: RevKeen.Invoice;
    requestId: string;
}
