// This file was auto-generated by Fern from our API Definition.

export interface MeterError {
    error: MeterError.Error_;
}

export namespace MeterError {
    export type Error_ =
        | string
        | {
              message: string;
              type: string;
          };
}
