// This file was auto-generated by Fern from our API Definition.

/**
 * Error response returned when a meter operation fails.
 */
export interface MeterError {
    error: MeterError.Error_;
}

export namespace MeterError {
    export type Error_ =
        | string
        | {
              message: string;
              type: string;
          };
}
