// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

export interface Order {
    /** Unique identifier for the order */
    id: string;
    /** Object type */
    object: Order.Object_;
    /** Public-facing order ID */
    public_id: string;
    /** ID of the customer */
    customer_id?: string | null;
    /** Order status. draft: Being built. pending: Awaiting payment. paid: Fully paid. partially_paid: Partial payment received. refunded: Refunded. canceled: Canceled. fulfilled: Shipped/delivered. */
    status: Order.Status;
    /** Billing type. one_time: Single purchase. recurring: Subscription-based. */
    billing_type: Order.BillingType;
    /** Fulfillment status for physical goods. */
    fulfillment_status?: Order.FulfillmentStatus | null;
    /** Three-letter ISO currency code */
    currency: string;
    /** Subtotal in cents */
    subtotal: number;
    /** Total discount in cents */
    discount: number;
    /** Total tax in cents */
    tax: number;
    /** Total amount in cents */
    total: number;
    /** Amount paid in cents */
    amount_paid: number;
    /** Amount refunded in cents */
    amount_refunded: number;
    /** Amount still due in cents */
    amount_due: number;
    line_items?: RevKeen.OrderLineItem[];
    /** Custom key-value metadata */
    metadata?: Record<string, unknown>;
    notes?: string | null;
    /** ID of the linked invoice (Commercial Truth) */
    invoice_id?: string | null;
    /** ID of the linked subscription (for recurring fulfillment) */
    subscription_id?: string | null;
    created_at: string;
    updated_at: string;
    paid_at?: string | null;
    canceled_at?: string | null;
    fulfilled_at?: string | null;
    expires_at?: string | null;
}

export namespace Order {
    /** Object type */
    export const Object_ = {
        Order: "order",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
    /** Order status. draft: Being built. pending: Awaiting payment. paid: Fully paid. partially_paid: Partial payment received. refunded: Refunded. canceled: Canceled. fulfilled: Shipped/delivered. */
    export const Status = {
        Draft: "draft",
        Pending: "pending",
        Paid: "paid",
        PartiallyPaid: "partially_paid",
        Refunded: "refunded",
        Canceled: "canceled",
        Fulfilled: "fulfilled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Billing type. one_time: Single purchase. recurring: Subscription-based. */
    export const BillingType = {
        OneTime: "one_time",
        Recurring: "recurring",
    } as const;
    export type BillingType = (typeof BillingType)[keyof typeof BillingType];
    /** Fulfillment status for physical goods. */
    export const FulfillmentStatus = {
        Unfulfilled: "unfulfilled",
        Partial: "partial",
        Fulfilled: "fulfilled",
        Returned: "returned",
    } as const;
    export type FulfillmentStatus = (typeof FulfillmentStatus)[keyof typeof FulfillmentStatus];
}
