// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

/**
 * A paginated list of orders matching the query filters.
 */
export interface OrderListResponse {
    object: OrderListResponse.Object_;
    data: RevKeen.Order[];
    has_more: boolean;
    total_count?: number;
}

export namespace OrderListResponse {
    export const Object_ = {
        List: "list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
