// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

export interface PaymentListResponse {
    object: PaymentListResponse.Object_;
    data: RevKeen.Payment[];
    has_more: boolean;
    total_count?: number;
}

export namespace PaymentListResponse {
    export const Object_ = {
        List: "list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
