// This file was auto-generated by Fern from our API Definition.
export var PaymentListResponse;
(function (PaymentListResponse) {
    PaymentListResponse.Object_ = {
        List: "list",
    };
})(PaymentListResponse || (PaymentListResponse = {}));
//# sourceMappingURL=PaymentListResponse.js.map