// This file was auto-generated by Fern from our API Definition.

/**
 * Error response returned when a payment operation fails.
 */
export interface PaymentErrorResponse {
    error: PaymentErrorResponse.Error_;
}

export namespace PaymentErrorResponse {
    export interface Error_ {
        type: string;
        code: string;
        message: string;
        param?: string;
    }
}
