// This file was auto-generated by Fern from our API Definition.

/**
 * Error response returned when a payment intent operation fails.
 */
export interface PaymentIntentErrorResponse {
    error: PaymentIntentErrorResponse.Error_;
}

export namespace PaymentIntentErrorResponse {
    export interface Error_ {
        /** Error type (api_error, invalid_request_error, etc.) */
        type: string;
        /** Error code */
        code: string;
        /** Human-readable error message */
        message: string;
        /** Parameter that caused the error */
        param?: string;
    }
}
