// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

/**
 * A saved payment instrument (card, bank account, etc.) attached to a customer for future charges.
 */
export interface PaymentMethod {
    /** Unique identifier for the payment method */
    id: string;
    /** Object type, always 'payment_method' */
    object: PaymentMethod.Object_;
    /** Public ID visible in API responses (pm_xxx format) */
    public_id: string | null;
    /** The type of payment method */
    type: PaymentMethod.Type;
    /** The status of the payment method */
    status: PaymentMethod.Status;
    /** ID of the customer this payment method belongs to */
    customer_id: string;
    /** Whether this is the customer's default payment method */
    is_default: boolean;
    card: RevKeen.CardDetails | null;
    us_bank_account: RevKeen.BankAccountDetails | null;
    billing_details: RevKeen.BillingDetails | null;
    /** Custom metadata attached to the payment method */
    metadata: Record<string, unknown>;
    /** When the payment method was created */
    created_at: string;
    /** When the payment method was last updated */
    updated_at: string;
}

export namespace PaymentMethod {
    /** Object type, always 'payment_method' */
    export const Object_ = {
        PaymentMethod: "payment_method",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
    /** The type of payment method */
    export const Type = {
        Card: "card",
        BankAccount: "bank_account",
        UsBankAccount: "us_bank_account",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** The status of the payment method */
    export const Status = {
        Active: "active",
        Inactive: "inactive",
        Expired: "expired",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
