// This file was auto-generated by Fern from our API Definition.

/**
 * A payment included in a payout settlement batch, with amount and fee details.
 */
export interface PayoutPayment {
    id: string;
    public_id: string | null;
    amount_minor: number;
    currency: string;
    status: string;
    kind: string | null;
    paid_at: string | null;
    created_at: string;
}
