// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

/**
 * The updated product object reflecting the changes.
 */
export interface ProductUpdateResponse {
    data: RevKeen.Product;
}
