// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

/**
 * The newly created product object.
 */
export interface ProductCreateResponse {
    data: RevKeen.Product;
}
