// This file was auto-generated by Fern from our API Definition.

export interface Refund {
    id: string;
    public_id: string;
    /** The original payment ID this refund is for (alias for parent_transaction_id) */
    payment_id: string;
    /** Parent transaction ID in unified transaction model. Same as payment_id for refunds. */
    parent_transaction_id: string;
    order_id: string | null;
    gateway: string;
    gateway_refund_id: string | null;
    /** Refund amount in cents */
    amount_minor: number;
    currency: string;
    reason: Refund.Reason | null;
    reason_details: string | null;
    status: Refund.Status;
    failure_reason: string | null;
    failure_code: string | null;
    processed_at: string | null;
    created_at: string;
}

export namespace Refund {
    export const Reason = {
        CustomerRequest: "customer_request",
        Duplicate: "duplicate",
        Fraudulent: "fraudulent",
        ProductNotReceived: "product_not_received",
        ProductUnacceptable: "product_unacceptable",
        SubscriptionCanceled: "subscription_canceled",
        Other: "other",
    } as const;
    export type Reason = (typeof Reason)[keyof typeof Reason];
    export const Status = {
        Pending: "pending",
        Processing: "processing",
        Succeeded: "succeeded",
        Failed: "failed",
        Canceled: "canceled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
