// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

export interface RefundListResponse {
    data: RevKeen.Refund[];
    meta: RefundListResponse.Meta;
}

export namespace RefundListResponse {
    export interface Meta {
        total: number;
        limit: number;
        offset: number;
        has_more: boolean;
    }
}
