// This file was auto-generated by Fern from our API Definition.
export var Refund;
(function (Refund) {
    Refund.Reason = {
        CustomerRequest: "customer_request",
        Duplicate: "duplicate",
        Fraudulent: "fraudulent",
        ProductNotReceived: "product_not_received",
        ProductUnacceptable: "product_unacceptable",
        SubscriptionCanceled: "subscription_canceled",
        Other: "other",
    };
    Refund.Status = {
        Pending: "pending",
        Processing: "processing",
        Succeeded: "succeeded",
        Failed: "failed",
        Canceled: "canceled",
    };
})(Refund || (Refund = {}));
//# sourceMappingURL=Refund.js.map