// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

export interface SetupIntentList {
    /** Object type, always 'list' */
    object: SetupIntentList.Object_;
    /** Array of setup intents */
    data: RevKeen.SetupIntent[];
    /** Whether there are more results available */
    has_more: boolean;
    /** Total count of matching setup intents */
    total_count: number;
    /** URL for this list resource */
    url: string;
}

export namespace SetupIntentList {
    /** Object type, always 'list' */
    export const Object_ = {
        List: "list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
