// This file was auto-generated by Fern from our API Definition.

/**
 * Action required from customer (3DS redirect, etc.)
 */
export interface SetupIntentNextAction {
    /** The type of action to take */
    type: SetupIntentNextAction.Type;
    /** Redirect details for 3DS authentication */
    redirect_to_url?: SetupIntentNextAction.RedirectToUrl;
    /** SDK-specific data for client-side handling */
    use_stripe_sdk?: Record<string, unknown>;
}

export namespace SetupIntentNextAction {
    /** The type of action to take */
    export const Type = {
        RedirectToUrl: "redirect_to_url",
        UseStripeSdk: "use_stripe_sdk",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];

    /**
     * Redirect details for 3DS authentication
     */
    export interface RedirectToUrl {
        /** The URL to redirect the customer to */
        url: string;
        /** The URL to redirect back to after completion */
        return_url: string;
    }
}
