// This file was auto-generated by Fern from our API Definition.
export var StaleUpdateResponse;
(function (StaleUpdateResponse) {
    StaleUpdateResponse.Reason = {
        StaleUpdate: "stale_update",
    };
})(StaleUpdateResponse || (StaleUpdateResponse = {}));
//# sourceMappingURL=StaleUpdateResponse.js.map