// This file was auto-generated by Fern from our API Definition.
export var SubscriptionItem;
(function (SubscriptionItem) {
    /** none: service (no order), physical: creates shipping order, digital: creates download order */
    SubscriptionItem.FulfillmentType = {
        None: "none",
        Physical: "physical",
        Digital: "digital",
    };
})(SubscriptionItem || (SubscriptionItem = {}));
//# sourceMappingURL=SubscriptionItem.js.map