// This file was auto-generated by Fern from our API Definition.

export interface SubscriptionScheduleErrorResponse {
    error: SubscriptionScheduleErrorResponse.Error_;
}

export namespace SubscriptionScheduleErrorResponse {
    export interface Error_ {
        /** Error type */
        type: string;
        /** Error code */
        code: string;
        /** Human-readable error message */
        message: string;
        /** Parameter that caused the error */
        param?: string;
    }
}
