// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

export interface SubscriptionScheduleListResponse {
    object: SubscriptionScheduleListResponse.Object_;
    data: RevKeen.SubscriptionSchedule[];
    has_more: boolean;
    /** The URL for accessing this list */
    url: string;
}

export namespace SubscriptionScheduleListResponse {
    export const Object_ = {
        List: "list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
