// This file was auto-generated by Fern from our API Definition.
export var SubscriptionScheduleListResponse;
(function (SubscriptionScheduleListResponse) {
    SubscriptionScheduleListResponse.Object_ = {
        List: "list",
    };
})(SubscriptionScheduleListResponse || (SubscriptionScheduleListResponse = {}));
//# sourceMappingURL=SubscriptionScheduleListResponse.js.map