// This file was auto-generated by Fern from our API Definition.

/**
 * Generic success confirmation for operations that do not return a resource.
 */
export interface SuccessResponse {
    success: boolean;
}
