// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

export interface TerminalPaymentListResponse {
    data: RevKeen.TerminalPayment[];
    meta: TerminalPaymentListResponse.Meta;
}

export namespace TerminalPaymentListResponse {
    export interface Meta {
        count: number;
        limit: number;
    }
}
