// This file was auto-generated by Fern from our API Definition.
export var TransactionListResponse;
(function (TransactionListResponse) {
    TransactionListResponse.Object_ = {
        List: "list",
    };
})(TransactionListResponse || (TransactionListResponse = {}));
//# sourceMappingURL=TransactionListResponse.js.map