// This file was auto-generated by Fern from our API Definition.

/**
 * Optional quantity transform (package pricing) applied before tier lookup.
 */
export interface TransformQuantity {
    /** Package size — quantity is divided by this value before pricing. Must be >= 1. Example: `divide_by: 10` with `round: up` charges per pack of 10. */
    divide_by: number;
    /** Rounding mode when quantity is not an exact multiple of `divide_by`. */
    round: TransformQuantity.Round;
}

export namespace TransformQuantity {
    /** Rounding mode when quantity is not an exact multiple of `divide_by`. */
    export const Round = {
        Up: "up",
        Down: "down",
    } as const;
    export type Round = (typeof Round)[keyof typeof Round];
}
