// This file was auto-generated by Fern from our API Definition.

export interface UsageEventListResponse {
    object: UsageEventListResponse.Object_;
    /** Array of usage event objects */
    data: Record<string, unknown>[];
    has_more: boolean;
}

export namespace UsageEventListResponse {
    export const Object_ = {
        List: "list",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
