// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../index.js";

export interface VoidListResponse {
    data: RevKeen.Void[];
    meta: VoidListResponse.Meta;
}

export namespace VoidListResponse {
    export interface Meta {
        total: number;
        limit: number;
        offset: number;
        has_more: boolean;
    }
}
