// This file was auto-generated by Fern from our API Definition.
export var WebhookEndpointUpdateResponse;
(function (WebhookEndpointUpdateResponse) {
    let Data;
    (function (Data) {
        Data.Status = {
            Enabled: "enabled",
            Disabled: "disabled",
        };
        /** Circuit breaker status - 'open' means deliveries are paused due to failures */
        Data.CircuitBreakerState = {
            Closed: "closed",
            Open: "open",
            HalfOpen: "half_open",
        };
    })(Data = WebhookEndpointUpdateResponse.Data || (WebhookEndpointUpdateResponse.Data = {}));
})(WebhookEndpointUpdateResponse || (WebhookEndpointUpdateResponse = {}));
//# sourceMappingURL=WebhookEndpointUpdateResponse.js.map