// This file was auto-generated by Fern from our API Definition.

export interface WebhookEndpoint {
    id: string;
    url: string;
    description: string | null;
    enabled_events: string[];
    status: WebhookEndpoint.Status;
    /** Signing secret. Returned only on create or secret rotation. */
    secret?: string;
    circuit_breaker_state: WebhookEndpoint.CircuitBreakerState;
    total_deliveries: number;
    successful_deliveries: number;
    failed_deliveries: number;
    last_delivery_at: string | null;
    created_at: string;
    updated_at: string;
}

export namespace WebhookEndpoint {
    export const Status = {
        Enabled: "enabled",
        Disabled: "disabled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export const CircuitBreakerState = {
        Closed: "closed",
        Open: "open",
        HalfOpen: "half_open",
    } as const;
    export type CircuitBreakerState = (typeof CircuitBreakerState)[keyof typeof CircuitBreakerState];
}
