// This file was auto-generated by Fern from our API Definition.
export var WebhookEndpoint;
(function (WebhookEndpoint) {
    WebhookEndpoint.Status = {
        Enabled: "enabled",
        Disabled: "disabled",
    };
    /** Circuit breaker status - 'open' means deliveries are paused due to failures */
    WebhookEndpoint.CircuitBreakerState = {
        Closed: "closed",
        Open: "open",
        HalfOpen: "half_open",
    };
})(WebhookEndpoint || (WebhookEndpoint = {}));
//# sourceMappingURL=WebhookEndpoint.js.map