// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../../../index.js";

export interface PayoutsListResponse {
    data: RevKeen.Payout[];
    meta: PayoutsListResponse.Meta;
}

export namespace PayoutsListResponse {
    export interface Meta {
        total: number;
        limit: number;
        offset: number;
        has_more: boolean;
    }
}
