// This file was auto-generated by Fern from our API Definition.
/** Filter by void status */
export const VoidsListRequestStatus = {
    Pending: "pending",
    Processing: "processing",
    Succeeded: "succeeded",
    Failed: "failed",
};
//# sourceMappingURL=VoidsListRequestStatus.js.map