// This file was auto-generated by Fern from our API Definition.

export interface CommsMessagesSendResponse {
    success: boolean;
    conversationId: string;
    messageId: string;
    notificationId: string;
    customerId: string;
}
