// This file was auto-generated by Fern from our API Definition.

/** Filter by dispute status */
export const DisputesListRequestStatus = {
    NeedsResponse: "needs_response",
    UnderReview: "under_review",
    Won: "won",
    Lost: "lost",
    WarningClosed: "warning_closed",
    WarningNeedsResponse: "warning_needs_response",
} as const;
export type DisputesListRequestStatus = (typeof DisputesListRequestStatus)[keyof typeof DisputesListRequestStatus];
