// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "seti_1a2b3c4d5e6f"
 *     }
 */
export interface CancelSetupIntentRequest {
    /** Setup Intent ID (UUID or public ID seti_xxx) */
    id: string;
    /** Reason for cancellation */
    cancellation_reason?: CancelSetupIntentRequest.CancellationReason;
}

export namespace CancelSetupIntentRequest {
    /** Reason for cancellation */
    export const CancellationReason = {
        Abandoned: "abandoned",
        RequestedByCustomer: "requested_by_customer",
        Duplicate: "duplicate",
    } as const;
    export type CancellationReason = (typeof CancellationReason)[keyof typeof CancellationReason];
}
