// This file was auto-generated by Fern from our API Definition.
export var CancelSetupIntentRequest;
(function (CancelSetupIntentRequest) {
    /** Reason for cancellation */
    CancelSetupIntentRequest.CancellationReason = {
        Abandoned: "abandoned",
        RequestedByCustomer: "requested_by_customer",
        Duplicate: "duplicate",
    };
})(CancelSetupIntentRequest || (CancelSetupIntentRequest = {}));
//# sourceMappingURL=CancelSetupIntentRequest.js.map