// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface CreateSetupIntentRequest {
    /** ID of the customer to attach the payment method to */
    customer_id?: string;
    /** Allowed payment method types */
    payment_method_types?: string[];
    /** How the payment method will be used */
    usage?: CreateSetupIntentRequest.Usage;
    /** Merchant description for reference */
    description?: string;
    /** Custom metadata to attach */
    metadata?: Record<string, unknown>;
}

export namespace CreateSetupIntentRequest {
    /** How the payment method will be used */
    export const Usage = {
        OnSession: "on_session",
        OffSession: "off_session",
    } as const;
    export type Usage = (typeof Usage)[keyof typeof Usage];
}
