// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface CustomersListRequest {
    /** Maximum number of results (1-100) */
    limit?: number;
    /** Number of results to skip */
    offset?: number | null;
    /** Search term to filter customers */
    search?: string;
}
