// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdatePaymentIntentRequest {
    /** Payment intent ID (pi_xxx) */
    id: string;
    /** Amount in cents */
    amount?: number;
    /** Three-letter ISO currency code */
    currency?: string;
    /** Payment method ID */
    payment_method?: string;
    /** Description for merchant reference */
    description?: string;
    /** Statement descriptor */
    statement_descriptor?: string;
    /** Statement descriptor suffix */
    statement_descriptor_suffix?: string;
    /** Email to send receipt to */
    receipt_email?: string;
    /** Custom key-value metadata */
    metadata?: Record<string, unknown>;
}
