// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         appKey: "quaderno"
 *     }
 */
export interface PostAppsAppKeyInstallRequest {
    appKey: string;
}
