// This file was auto-generated by Fern from our API Definition.
import { normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as RevKeen from "../../../index.js";
/**
 * Cancel unsettled transactions before gateway settlement. Voids are always for the full amount — no partial voids. If the transaction has already settled, use a refund instead.
 *
 * **Required Scopes:**
 * - `voids:read` - List and retrieve voids
 * - `voids:write` - Create voids
 */
export class VoidsClient {
    constructor(options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }
    /**
     * Retrieve a paginated list of voids with optional filters. Results are ordered by creation date (newest first). Voids are full-amount cancellations of unsettled transactions.
     *
     * @param {RevKeen.VoidsListRequest} request
     * @param {VoidsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.voids.list({
     *         created_after: "2024-01-01T00:00:00Z",
     *         created_before: "2024-12-31T23:59:59Z",
     *         limit: 20
     *     })
     */
    list(request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }
    async __list(request = {}, requestOptions) {
        const { status, payment_id: paymentId, gateway, created_after: createdAfter, created_before: createdBefore, limit, offset, } = request;
        const _queryParams = {
            status: status != null ? status : undefined,
            payment_id: paymentId,
            gateway,
            created_after: createdAfter,
            created_before: createdBefore,
            limit,
            offset,
        };
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, "voids"),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/voids");
    }
    /**
     * Void a payment that has not yet settled. Voids are always for the full amount. If the payment has already settled, use a refund instead.
     *
     * @param {RevKeen.CreateVoidInput} request
     * @param {VoidsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.voids.create({
     *         payment_id: "660e8400-e29b-41d4-a716-446655440000"
     *     })
     */
    create(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }
    async __create(request, requestOptions) {
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, "voids"),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/voids");
    }
    /**
     * Retrieve a single void by its public ID (void_xxx) or internal UUID.
     *
     * @param {RevKeen.VoidsRetrieveRequest} request
     * @param {VoidsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.voids.retrieve({
     *         id: "id"
     *     })
     */
    retrieve(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }
    async __retrieve(request, requestOptions) {
        const { id } = request;
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, `voids/${core.url.encodePathParam(id)}`),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/voids/{id}");
    }
}
//# sourceMappingURL=Client.js.map