// This file was auto-generated by Fern from our API Definition.
export var CustomersOrdersListResponse;
(function (CustomersOrdersListResponse) {
    CustomersOrdersListResponse.Object_ = {
        List: "list",
    };
})(CustomersOrdersListResponse || (CustomersOrdersListResponse = {}));
//# sourceMappingURL=CustomersOrdersListResponse.js.map