// This file was auto-generated by Fern from our API Definition.

export interface CustomersExternalBatchResponse {
    /** Number of customers created */
    created: number;
    /** Number of customers updated */
    updated: number;
    /** Number of customers skipped due to stale data */
    skipped: number;
    /** List of failed customers with error messages */
    failed: CustomersExternalBatchResponse.Failed.Item[];
}

export namespace CustomersExternalBatchResponse {
    export type Failed = Failed.Item[];

    export namespace Failed {
        export interface Item {
            external_id: string;
            error: string;
        }
    }
}
