// This file was auto-generated by Fern from our API Definition.
export var CustomersInvoicesListResponse;
(function (CustomersInvoicesListResponse) {
    CustomersInvoicesListResponse.Object_ = {
        List: "list",
    };
})(CustomersInvoicesListResponse || (CustomersInvoicesListResponse = {}));
//# sourceMappingURL=CustomersInvoicesListResponse.js.map