// This file was auto-generated by Fern from our API Definition.
export var CustomersSubscriptionsListResponse;
(function (CustomersSubscriptionsListResponse) {
    CustomersSubscriptionsListResponse.Object_ = {
        List: "list",
    };
})(CustomersSubscriptionsListResponse || (CustomersSubscriptionsListResponse = {}));
//# sourceMappingURL=CustomersSubscriptionsListResponse.js.map