// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface AnalyticsCheckoutAbandonmentListRequest {
    /** Filter by alert status */
    status?: RevKeen.AnalyticsCheckoutAbandonmentListRequestStatus;
    /** Filter by severity level */
    severity?: RevKeen.AnalyticsCheckoutAbandonmentListRequestSeverity;
    /** Page number */
    page?: number;
    /** Results per page (1-100) */
    pageSize?: number;
}
