// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         customerId: "customerId"
 *     }
 */
export interface AnalyticsCustomersRetrieveRequest {
    /** Customer UUID */
    customerId: string;
}
