// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         topN: 10
 *     }
 */
export interface AnalyticsCustomersGetLtvRequest {
    /** Number of top customers to return (1-100) */
    topN?: number;
}
