// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as RevKeen from "../../../index.js";

export declare namespace IntegrationsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Manage external integrations (PracticeHub, Wodify). List active integrations and update status.
 */
export class IntegrationsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<IntegrationsClient.Options>;

    constructor(options: IntegrationsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Activate an external integration for the merchant. Validates credentials and schedules sync.
     *
     * @param {RevKeen.IntegrationsActivateRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.ConflictError}
     *
     * @example
     *     await client.integrations.activate({
     *         provider: "practicehub",
     *         credentials: {
     *             apiKey: "apiKey",
     *             baseUrl: "baseUrl"
     *         }
     *     })
     */
    public activate(
        request: RevKeen.IntegrationsActivateRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsActivateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__activate(request, requestOptions));
    }

    private async __activate(
        request: RevKeen.IntegrationsActivateRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsActivateResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/activate`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.IntegrationsActivateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new RevKeen.ConflictError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/integrations/{provider}/activate",
        );
    }

    /**
     * Deactivate an external integration. Stops sync jobs and revokes API keys.
     *
     * @param {RevKeen.IntegrationsDeactivateRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.deactivate({
     *         provider: "practicehub"
     *     })
     */
    public deactivate(
        request: RevKeen.IntegrationsDeactivateRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsDeactivateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deactivate(request, requestOptions));
    }

    private async __deactivate(
        request: RevKeen.IntegrationsDeactivateRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsDeactivateResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/deactivate`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsDeactivateResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/integrations/{provider}/deactivate",
        );
    }

    /**
     * Get the current status of an integration including sync schedule.
     *
     * @param {RevKeen.IntegrationsGetStatusRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.integrations.getstatus({
     *         provider: "practicehub"
     *     })
     */
    public getstatus(
        request: RevKeen.IntegrationsGetStatusRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsGetStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getstatus(request, requestOptions));
    }

    private async __getstatus(
        request: RevKeen.IntegrationsGetStatusRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsGetStatusResponse>> {
        const { provider } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsGetStatusResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/integrations/{provider}");
    }

    /**
     * Validate credentials against the provider without activating the integration.
     *
     * @param {RevKeen.IntegrationsTestRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     *
     * @example
     *     await client.integrations.test({
     *         provider: "practicehub",
     *         credentials: {
     *             apiKey: "apiKey",
     *             baseUrl: "baseUrl"
     *         }
     *     })
     */
    public test(
        request: RevKeen.IntegrationsTestRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsTestResponse> {
        return core.HttpResponsePromise.fromPromise(this.__test(request, requestOptions));
    }

    private async __test(
        request: RevKeen.IntegrationsTestRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsTestResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/test`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.IntegrationsTestResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/integrations/{provider}/test",
        );
    }

    /**
     * Trigger an immediate sync job for an active integration. Pass fullResync=true to ignore the incremental cursor and re-process all records.
     *
     * @param {RevKeen.IntegrationsTriggerSyncRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     *
     * @example
     *     await client.integrations.triggersync({
     *         provider: "practicehub"
     *     })
     */
    public triggersync(
        request: RevKeen.IntegrationsTriggerSyncRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsTriggerSyncResponse> {
        return core.HttpResponsePromise.fromPromise(this.__triggersync(request, requestOptions));
    }

    private async __triggersync(
        request: RevKeen.IntegrationsTriggerSyncRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsTriggerSyncResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/sync`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsTriggerSyncResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/integrations/{provider}/sync",
        );
    }

    /**
     * List all integrations for the authenticated merchant.
     *
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     *
     * @example
     *     await client.integrations.list()
     */
    public list(
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsListResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                "integrations",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.IntegrationsListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/integrations");
    }

    /**
     * Update integration status and last sync timestamp. Used by sync worker.
     *
     * @param {RevKeen.IntegrationsUpdateStatusRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.integrations.updatestatus({
     *         provider: "practicehub",
     *         status: "connected"
     *     })
     */
    public updatestatus(
        request: RevKeen.IntegrationsUpdateStatusRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsUpdateStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updatestatus(request, requestOptions));
    }

    private async __updatestatus(
        request: RevKeen.IntegrationsUpdateStatusRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsUpdateStatusResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/status`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsUpdateStatusResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/integrations/{provider}/status",
        );
    }

    /**
     * Enable or disable sync for an integration.
     *
     * @param {RevKeen.IntegrationsSyncToggleRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.synctoggle({
     *         provider: "practicehub",
     *         enabled: true
     *     })
     */
    public synctoggle(
        request: RevKeen.IntegrationsSyncToggleRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsSyncToggleResponse> {
        return core.HttpResponsePromise.fromPromise(this.__synctoggle(request, requestOptions));
    }

    private async __synctoggle(
        request: RevKeen.IntegrationsSyncToggleRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsSyncToggleResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/sync-toggle`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsSyncToggleResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/integrations/{provider}/sync-toggle",
        );
    }

    /**
     * Update the sync interval (in minutes) for an integration.
     *
     * @param {RevKeen.IntegrationsSyncIntervalRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.syncinterval({
     *         provider: "practicehub",
     *         syncIntervalMinutes: 1
     *     })
     */
    public syncinterval(
        request: RevKeen.IntegrationsSyncIntervalRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsSyncIntervalResponse> {
        return core.HttpResponsePromise.fromPromise(this.__syncinterval(request, requestOptions));
    }

    private async __syncinterval(
        request: RevKeen.IntegrationsSyncIntervalRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsSyncIntervalResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/sync-interval`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsSyncIntervalResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/integrations/{provider}/sync-interval",
        );
    }

    /**
     * Update how far back (in days) to fetch invoices on initial sync.
     *
     * @param {RevKeen.IntegrationsInvoiceLookbackRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.invoicelookback({
     *         provider: "practicehub",
     *         invoiceLookbackDays: 1
     *     })
     */
    public invoicelookback(
        request: RevKeen.IntegrationsInvoiceLookbackRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsInvoiceLookbackResponse> {
        return core.HttpResponsePromise.fromPromise(this.__invoicelookback(request, requestOptions));
    }

    private async __invoicelookback(
        request: RevKeen.IntegrationsInvoiceLookbackRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsInvoiceLookbackResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/invoice-lookback`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsInvoiceLookbackResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/integrations/{provider}/invoice-lookback",
        );
    }

    /**
     * Enable or disable automatic invoice email sending on sync.
     *
     * @param {RevKeen.IntegrationsAutoSendInvoicesRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.autosendinvoices({
     *         provider: "practicehub",
     *         autoSendInvoices: true
     *     })
     */
    public autosendinvoices(
        request: RevKeen.IntegrationsAutoSendInvoicesRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsAutoSendInvoicesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__autosendinvoices(request, requestOptions));
    }

    private async __autosendinvoices(
        request: RevKeen.IntegrationsAutoSendInvoicesRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsAutoSendInvoicesResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/auto-send-invoices`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsAutoSendInvoicesResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/integrations/{provider}/auto-send-invoices",
        );
    }

    /**
     * Update payment method mappings between RevKeen and the external provider.
     *
     * @param {RevKeen.IntegrationsPaymentMappingsRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.paymentmappings({
     *         provider: "practicehub",
     *         mappings: [{
     *                 id: "id",
     *                 revkeenMethod: "revkeenMethod",
     *                 practiceHubMethodId: "practiceHubMethodId"
     *             }]
     *     })
     */
    public paymentmappings(
        request: RevKeen.IntegrationsPaymentMappingsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsPaymentMappingsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__paymentmappings(request, requestOptions));
    }

    private async __paymentmappings(
        request: RevKeen.IntegrationsPaymentMappingsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsPaymentMappingsResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/payment-mappings`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsPaymentMappingsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/integrations/{provider}/payment-mappings",
        );
    }

    /**
     * Fetch payment methods from the external provider using stored credentials.
     *
     * @param {RevKeen.IntegrationsGetPaymentMethodsRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.getpaymentmethods({
     *         provider: "practicehub"
     *     })
     */
    public getpaymentmethods(
        request: RevKeen.IntegrationsGetPaymentMethodsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsGetPaymentMethodsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getpaymentmethods(request, requestOptions));
    }

    private async __getpaymentmethods(
        request: RevKeen.IntegrationsGetPaymentMethodsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsGetPaymentMethodsResponse>> {
        const { provider } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/payment-methods`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsGetPaymentMethodsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/integrations/{provider}/payment-methods",
        );
    }

    /**
     * Fetch payment methods from the external provider using temporary credentials, typically during integration setup wizard.
     *
     * @param {RevKeen.IntegrationsPostPaymentMethodsRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.integrations.postpaymentmethods({
     *         provider: "practicehub",
     *         baseUrl: "baseUrl",
     *         apiKey: "apiKey"
     *     })
     */
    public postpaymentmethods(
        request: RevKeen.IntegrationsPostPaymentMethodsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsPostPaymentMethodsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postpaymentmethods(request, requestOptions));
    }

    private async __postpaymentmethods(
        request: RevKeen.IntegrationsPostPaymentMethodsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsPostPaymentMethodsResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/payment-methods`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsPostPaymentMethodsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/integrations/{provider}/payment-methods",
        );
    }

    /**
     * Get per-resource sync state for an integration (patients, invoices, products, etc.).
     *
     * @param {RevKeen.IntegrationsSyncStatesRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.integrations.syncstates({
     *         provider: "practicehub"
     *     })
     */
    public syncstates(
        request: RevKeen.IntegrationsSyncStatesRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsSyncStatesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__syncstates(request, requestOptions));
    }

    private async __syncstates(
        request: RevKeen.IntegrationsSyncStatesRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsSyncStatesResponse>> {
        const { provider } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/sync-states`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsSyncStatesResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/integrations/{provider}/sync-states",
        );
    }

    /**
     * List sync logs with filtering for the Sync History dashboard.
     *
     * @param {RevKeen.IntegrationsSyncLogsRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.integrations.synclogs({
     *         provider: "practicehub"
     *     })
     */
    public synclogs(
        request: RevKeen.IntegrationsSyncLogsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsSyncLogsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__synclogs(request, requestOptions));
    }

    private async __synclogs(
        request: RevKeen.IntegrationsSyncLogsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsSyncLogsResponse>> {
        const {
            provider,
            integrationId,
            resourceType,
            status,
            jobType,
            createdAfter,
            createdBefore,
            limit,
            offset,
            latestOnly,
        } = request;
        const _queryParams: Record<string, unknown> = {
            integrationId,
            resourceType,
            status: status != null ? status : undefined,
            jobType: jobType != null ? jobType : undefined,
            createdAfter,
            createdBefore,
            limit,
            offset,
            latestOnly: latestOnly != null ? latestOnly : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/sync-logs`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.IntegrationsSyncLogsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/integrations/{provider}/sync-logs",
        );
    }

    /**
     * Get a single sync log entry by its ID.
     *
     * @param {RevKeen.IntegrationsSyncLogByIdRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.synclogbyid({
     *         provider: "practicehub",
     *         logId: "logId"
     *     })
     */
    public synclogbyid(
        request: RevKeen.IntegrationsSyncLogByIdRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsSyncLogByIdResponse> {
        return core.HttpResponsePromise.fromPromise(this.__synclogbyid(request, requestOptions));
    }

    private async __synclogbyid(
        request: RevKeen.IntegrationsSyncLogByIdRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsSyncLogByIdResponse>> {
        const { provider, logId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/sync-logs/${core.url.encodePathParam(logId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsSyncLogByIdResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/integrations/{provider}/sync-logs/{logId}",
        );
    }

    /**
     * Get aggregate sync statistics for an integration.
     *
     * @param {RevKeen.IntegrationsSyncStatsRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.integrations.syncstats({
     *         provider: "practicehub",
     *         integrationId: "integrationId"
     *     })
     */
    public syncstats(
        request: RevKeen.IntegrationsSyncStatsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsSyncStatsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__syncstats(request, requestOptions));
    }

    private async __syncstats(
        request: RevKeen.IntegrationsSyncStatsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsSyncStatsResponse>> {
        const { provider, integrationId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/sync-stats/${core.url.encodePathParam(integrationId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsSyncStatsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/integrations/{provider}/sync-stats/{integrationId}",
        );
    }

    /**
     * Get sync statistics grouped by resource type for an integration.
     *
     * @param {RevKeen.IntegrationsSyncStatsByTypeRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.integrations.syncstatsbytype({
     *         provider: "practicehub",
     *         integrationId: "integrationId"
     *     })
     */
    public syncstatsbytype(
        request: RevKeen.IntegrationsSyncStatsByTypeRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsSyncStatsByTypeResponse> {
        return core.HttpResponsePromise.fromPromise(this.__syncstatsbytype(request, requestOptions));
    }

    private async __syncstatsbytype(
        request: RevKeen.IntegrationsSyncStatsByTypeRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsSyncStatsByTypeResponse>> {
        const { provider, integrationId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/sync-stats-by-type/${core.url.encodePathParam(integrationId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsSyncStatsByTypeResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/integrations/{provider}/sync-stats-by-type/{integrationId}",
        );
    }

    /**
     * Request retry for a failed sync log item.
     *
     * @param {RevKeen.IntegrationsRetryLogRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.retrylog({
     *         provider: "practicehub",
     *         logId: "logId"
     *     })
     */
    public retrylog(
        request: RevKeen.IntegrationsRetryLogRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsRetryLogResponse> {
        return core.HttpResponsePromise.fromPromise(this.__retrylog(request, requestOptions));
    }

    private async __retrylog(
        request: RevKeen.IntegrationsRetryLogRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsRetryLogResponse>> {
        const { provider, logId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/sync-logs/${core.url.encodePathParam(logId)}/retry`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.IntegrationsRetryLogResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/integrations/{provider}/sync-logs/{logId}/retry",
        );
    }

    /**
     * Request batch retry for failed sync log items of an integration.
     *
     * @param {RevKeen.IntegrationsBatchRetryRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.integrations.batchretry({
     *         provider: "practicehub",
     *         integrationId: "integrationId"
     *     })
     */
    public batchretry(
        request: RevKeen.IntegrationsBatchRetryRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsBatchRetryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__batchretry(request, requestOptions));
    }

    private async __batchretry(
        request: RevKeen.IntegrationsBatchRetryRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsBatchRetryResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/sync-logs/batch-retry`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsBatchRetryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/integrations/{provider}/sync-logs/batch-retry",
        );
    }

    /**
     * Fetch packages from the external provider using stored credentials.
     *
     * @param {RevKeen.IntegrationsGetPackagesRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.getpackages({
     *         provider: "practicehub"
     *     })
     */
    public getpackages(
        request: RevKeen.IntegrationsGetPackagesRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsGetPackagesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getpackages(request, requestOptions));
    }

    private async __getpackages(
        request: RevKeen.IntegrationsGetPackagesRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsGetPackagesResponse>> {
        const { provider } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/packages`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsGetPackagesResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/integrations/{provider}/packages",
        );
    }

    /**
     * List product mappings between external packages and RevKeen products.
     *
     * @param {RevKeen.IntegrationsGetProductMappingsRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.getproductmappings({
     *         provider: "practicehub"
     *     })
     */
    public getproductmappings(
        request: RevKeen.IntegrationsGetProductMappingsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsGetProductMappingsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getproductmappings(request, requestOptions));
    }

    private async __getproductmappings(
        request: RevKeen.IntegrationsGetProductMappingsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsGetProductMappingsResponse>> {
        const { provider } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/product-mappings`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsGetProductMappingsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/integrations/{provider}/product-mappings",
        );
    }

    /**
     * Save product mappings between external packages and RevKeen products. Replaces all existing mappings in a single transaction.
     *
     * @param {RevKeen.IntegrationsPutProductMappingsRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.putproductmappings({
     *         provider: "practicehub",
     *         mappings: [{
     *                 externalId: "externalId",
     *                 internalId: "internalId"
     *             }]
     *     })
     */
    public putproductmappings(
        request: RevKeen.IntegrationsPutProductMappingsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsPutProductMappingsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__putproductmappings(request, requestOptions));
    }

    private async __putproductmappings(
        request: RevKeen.IntegrationsPutProductMappingsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsPutProductMappingsResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/product-mappings`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsPutProductMappingsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/integrations/{provider}/product-mappings",
        );
    }

    /**
     * Delete a single product mapping by external ID.
     *
     * @param {RevKeen.IntegrationsDeleteProductMappingRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.deleteproductmapping({
     *         provider: "practicehub",
     *         externalId: "externalId"
     *     })
     */
    public deleteproductmapping(
        request: RevKeen.IntegrationsDeleteProductMappingRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsDeleteProductMappingResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteproductmapping(request, requestOptions));
    }

    private async __deleteproductmapping(
        request: RevKeen.IntegrationsDeleteProductMappingRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsDeleteProductMappingResponse>> {
        const { provider, externalId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/product-mappings/${core.url.encodePathParam(externalId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsDeleteProductMappingResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/integrations/{provider}/product-mappings/{externalId}",
        );
    }

    /**
     * Fetch all line items and deduplicate by billable_item_id to discover items missing from packages.
     *
     * @param {RevKeen.IntegrationsGetBillableItemsRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.integrations.getbillableitems({
     *         provider: "practicehub"
     *     })
     */
    public getbillableitems(
        request: RevKeen.IntegrationsGetBillableItemsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsGetBillableItemsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getbillableitems(request, requestOptions));
    }

    private async __getbillableitems(
        request: RevKeen.IntegrationsGetBillableItemsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsGetBillableItemsResponse>> {
        const { provider } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/billable-items`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsGetBillableItemsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/integrations/{provider}/billable-items",
        );
    }

    /**
     * Use AI to suggest mappings between external items and RevKeen products.
     *
     * @param {RevKeen.IntegrationsSuggestMappingsRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     *
     * @example
     *     await client.integrations.suggestmappings({
     *         provider: "practicehub",
     *         externalItems: [{
     *                 id: "id",
     *                 name: "name",
     *                 source: "package"
     *             }]
     *     })
     */
    public suggestmappings(
        request: RevKeen.IntegrationsSuggestMappingsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsSuggestMappingsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__suggestmappings(request, requestOptions));
    }

    private async __suggestmappings(
        request: RevKeen.IntegrationsSuggestMappingsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsSuggestMappingsResponse>> {
        const { provider, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/suggest-mappings`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsSuggestMappingsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/integrations/{provider}/suggest-mappings",
        );
    }

    /**
     * Returns unresolved unmapped transaction attempts aggregated per external package.
     *
     * @param {RevKeen.IntegrationsGetUnmappedAttemptsRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.integrations.getunmappedattempts({
     *         provider: "practicehub"
     *     })
     */
    public getunmappedattempts(
        request: RevKeen.IntegrationsGetUnmappedAttemptsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsGetUnmappedAttemptsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getunmappedattempts(request, requestOptions));
    }

    private async __getunmappedattempts(
        request: RevKeen.IntegrationsGetUnmappedAttemptsRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsGetUnmappedAttemptsResponse>> {
        const { provider } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/unmapped-attempts`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsGetUnmappedAttemptsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/integrations/{provider}/unmapped-attempts",
        );
    }

    /**
     * Reset the circuit breaker (consecutive errors) and trigger an immediate sync.
     *
     * @param {RevKeen.IntegrationsResumeSyncRequest} request
     * @param {IntegrationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.integrations.resumesync({
     *         provider: "practicehub"
     *     })
     */
    public resumesync(
        request: RevKeen.IntegrationsResumeSyncRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.IntegrationsResumeSyncResponse> {
        return core.HttpResponsePromise.fromPromise(this.__resumesync(request, requestOptions));
    }

    private async __resumesync(
        request: RevKeen.IntegrationsResumeSyncRequest,
        requestOptions?: IntegrationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.IntegrationsResumeSyncResponse>> {
        const { provider } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `integrations/${core.url.encodePathParam(provider)}/resume-sync`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.IntegrationsResumeSyncResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/integrations/{provider}/resume-sync",
        );
    }
}
