// This file was auto-generated by Fern from our API Definition.
export var ArchivePaymentLinkResponse;
(function (ArchivePaymentLinkResponse) {
    ArchivePaymentLinkResponse.Status = {
        Active: "active",
        Inactive: "inactive",
        Archived: "archived",
    };
})(ArchivePaymentLinkResponse || (ArchivePaymentLinkResponse = {}));
//# sourceMappingURL=ArchivePaymentLinkResponse.js.map