// This file was auto-generated by Fern from our API Definition.
export var ExpirePaymentLinkResponse;
(function (ExpirePaymentLinkResponse) {
    ExpirePaymentLinkResponse.Mode = {
        Invoice: "invoice",
        Subscription: "subscription",
        Custom: "custom",
    };
    ExpirePaymentLinkResponse.Status = {
        Draft: "draft",
        Active: "active",
        Expired: "expired",
        Completed: "completed",
    };
    let LineItems;
    (function (LineItems) {
        let Item;
        (function (Item) {
            let ProductDetails;
            (function (ProductDetails) {
                let Recurring;
                (function (Recurring) {
                    Recurring.Interval = {
                        Day: "day",
                        Week: "week",
                        Month: "month",
                        Year: "year",
                    };
                })(Recurring = ProductDetails.Recurring || (ProductDetails.Recurring = {}));
            })(ProductDetails = Item.ProductDetails || (Item.ProductDetails = {}));
        })(Item = LineItems.Item || (LineItems.Item = {}));
    })(LineItems = ExpirePaymentLinkResponse.LineItems || (ExpirePaymentLinkResponse.LineItems = {}));
    ExpirePaymentLinkResponse.TaxBehavior = {
        Exclusive: "exclusive",
        Inclusive: "inclusive",
        Unspecified: "unspecified",
    };
})(ExpirePaymentLinkResponse || (ExpirePaymentLinkResponse = {}));
//# sourceMappingURL=ExpirePaymentLinkResponse.js.map