// This file was auto-generated by Fern from our API Definition.

export const ListPaymentLinksRequestMode = {
    Invoice: "invoice",
    Subscription: "subscription",
    Custom: "custom",
} as const;
export type ListPaymentLinksRequestMode =
    (typeof ListPaymentLinksRequestMode)[keyof typeof ListPaymentLinksRequestMode];
