// This file was auto-generated by Fern from our API Definition.
export const ListPaymentLinksRequestStatus = {
    Draft: "draft",
    Active: "active",
    Expired: "expired",
    Completed: "completed",
};
//# sourceMappingURL=ListPaymentLinksRequestStatus.js.map