// This file was auto-generated by Fern from our API Definition.
export var InvoicesCreateRequest;
(function (InvoicesCreateRequest) {
    let AllowedMethods;
    (function (AllowedMethods) {
        AllowedMethods.Item = {
            Card: "card",
            InStore: "in_store",
        };
    })(AllowedMethods = InvoicesCreateRequest.AllowedMethods || (InvoicesCreateRequest.AllowedMethods = {}));
})(InvoicesCreateRequest || (InvoicesCreateRequest = {}));
//# sourceMappingURL=InvoicesCreateRequest.js.map