// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface InvoicesUpdateRequest {
    id: string;
    status?: string;
    total_minor?: number;
    due_date?: string;
    /** Subscription billing terms — set to null to remove */
    subscription_terms?: InvoicesUpdateRequest.SubscriptionTerms | null;
}

export namespace InvoicesUpdateRequest {
    /**
     * Subscription billing terms — set to null to remove
     */
    export interface SubscriptionTerms {
        /** How to collect payment for recurring invoices */
        collection_method: SubscriptionTerms.CollectionMethod;
        /** When the subscription billing cycle starts */
        start_mode: SubscriptionTerms.StartMode;
        /** Start date (ISO 8601) — required when start_mode is 'specific_date' */
        start_date?: string;
        /** How the subscription duration is determined */
        duration_type: SubscriptionTerms.DurationType;
        /** Number of billing cycles — required when duration_type is 'fixed_cycles' */
        duration_count?: number;
        /** End date (ISO 8601) — required when duration_type is 'end_date' */
        end_date?: string;
        /** Whether to charge the first cycle immediately or defer to the start date */
        first_payment_behavior: SubscriptionTerms.FirstPaymentBehavior;
    }

    export namespace SubscriptionTerms {
        /** How to collect payment for recurring invoices */
        export const CollectionMethod = {
            ChargeAutomatically: "charge_automatically",
            SendInvoice: "send_invoice",
        } as const;
        export type CollectionMethod = (typeof CollectionMethod)[keyof typeof CollectionMethod];
        /** When the subscription billing cycle starts */
        export const StartMode = {
            WhenPaid: "when_paid",
            OnInvoiceDate: "on_invoice_date",
            FirstOfNextMonth: "first_of_next_month",
            SpecificDate: "specific_date",
        } as const;
        export type StartMode = (typeof StartMode)[keyof typeof StartMode];
        /** How the subscription duration is determined */
        export const DurationType = {
            UntilCancelled: "until_cancelled",
            FixedCycles: "fixed_cycles",
            EndDate: "end_date",
        } as const;
        export type DurationType = (typeof DurationType)[keyof typeof DurationType];
        /** Whether to charge the first cycle immediately or defer to the start date */
        export const FirstPaymentBehavior = {
            ChargeFirstCycleNow: "charge_first_cycle_now",
            DeferFirstCycleToStartDate: "defer_first_cycle_to_start_date",
        } as const;
        export type FirstPaymentBehavior = (typeof FirstPaymentBehavior)[keyof typeof FirstPaymentBehavior];
    }
}
