// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         reason: "Invoice totals do not match purchase order"
 *     }
 */
export interface InvoicesRejectRequest {
    id: string;
    /** Reason for rejecting the invoice (required) */
    reason: string;
}
