// This file was auto-generated by Fern from our API Definition.
export var InvoicesPayRequest;
(function (InvoicesPayRequest) {
    /** The payment method used */
    InvoicesPayRequest.PaymentMethod = {
        Cash: "cash",
        Check: "check",
        BankTransfer: "bank_transfer",
        Other: "other",
    };
})(InvoicesPayRequest || (InvoicesPayRequest = {}));
//# sourceMappingURL=InvoicesPayRequest.js.map