// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface InvoicesSendRequest {
    id: string;
    /** Communication channel to send the invoice through */
    channel?: InvoicesSendRequest.Channel;
    /** Optional custom template ID to use for the notification */
    template_id?: string;
}

export namespace InvoicesSendRequest {
    /** Communication channel to send the invoice through */
    export const Channel = {
        Email: "email",
        Sms: "sms",
        Whatsapp: "whatsapp",
    } as const;
    export type Channel = (typeof Channel)[keyof typeof Channel];
}
