// This file was auto-generated by Fern from our API Definition.

/** Filter by status */
export const ListSetupIntentsRequestStatus = {
    RequiresPaymentMethod: "requires_payment_method",
    RequiresConfirmation: "requires_confirmation",
    RequiresAction: "requires_action",
    Processing: "processing",
    Succeeded: "succeeded",
    Canceled: "canceled",
} as const;
export type ListSetupIntentsRequestStatus =
    (typeof ListSetupIntentsRequestStatus)[keyof typeof ListSetupIntentsRequestStatus];
