// This file was auto-generated by Fern from our API Definition.
/** Filter by price type */
export const PricesListRequestType = {
    OneTime: "one_time",
    Recurring: "recurring",
};
//# sourceMappingURL=PricesListRequestType.js.map