// This file was auto-generated by Fern from our API Definition.

/** Filter by pricing model */
export const PricesListRequestPricingModel = {
    Fixed: "fixed",
    PayWhatYouWant: "pay_what_you_want",
    Free: "free",
} as const;
export type PricesListRequestPricingModel =
    (typeof PricesListRequestPricingModel)[keyof typeof PricesListRequestPricingModel];
