// This file was auto-generated by Fern from our API Definition.
export var CreateProductRequest;
(function (CreateProductRequest) {
    CreateProductRequest.Kind = {
        Subscription: "subscription",
        OneTime: "one_time",
        Usage: "usage",
    };
    CreateProductRequest.PricingModel = {
        OneTime: "one_time",
        Recurring: "recurring",
        Usage: "usage",
    };
    /** Fulfillment type for the product. Defaults to 'none' (service). */
    CreateProductRequest.FulfillmentType = {
        None: "none",
        Digital: "digital",
        Physical: "physical",
    };
    /** How billing dates are calculated. same_day: Bill on same day as start. day_of_month: Bill on specific day (1-31). last_day: Bill on last day of month. */
    CreateProductRequest.BillingAnchorRule = {
        SameDay: "same_day",
        DayOfMonth: "day_of_month",
        LastDay: "last_day",
    };
    /** When first payment is collected. immediate: Charge on start. next_anchor: Charge on first scheduled date. prorate: Prorate until first date. */
    CreateProductRequest.FirstChargeBehavior = {
        Immediate: "immediate",
        NextAnchor: "next_anchor",
        Prorate: "prorate",
    };
    /** How subscription ends. until_canceled: Runs forever. fixed_payments: Ends after N billing cycles. */
    CreateProductRequest.EndBehavior = {
        UntilCanceled: "until_canceled",
        FixedPayments: "fixed_payments",
    };
})(CreateProductRequest || (CreateProductRequest = {}));
//# sourceMappingURL=CreateProductRequest.js.map