// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         source: "practicehub",
 *         products: [{
 *                 external_id: "prod_12345",
 *                 name: "Monthly Membership",
 *                 amount_cents: 9900
 *             }]
 *     }
 */
export interface ProductsExternalBatchRequest {
    /** Integration source (e.g., practicehub, wodify) */
    source: string;
    /** Array of products to upsert (max 100) */
    products: ProductsExternalBatchRequest.Products.Item[];
}

export namespace ProductsExternalBatchRequest {
    export type Products = Products.Item[];

    export namespace Products {
        export interface Item {
            /** External system's product ID */
            external_id: string;
            /** Product name */
            name: string;
            /** Product description */
            description?: string;
            /** Product kind - subscription or one-time */
            kind?: Item.Kind;
            /** Price in minor units (cents) */
            amount_cents: number;
            /** ISO 4217 currency code */
            currency?: string;
            /** Whether the product is active */
            is_active?: boolean;
            /** Billing interval for subscriptions */
            interval?: Item.Interval;
            /** Number of intervals between billings */
            interval_count?: number;
            /** External system's last update timestamp for stale update protection */
            external_updated_at?: string;
            /** Additional external reference (e.g., membership ID) */
            external_ref?: string;
            /** Additional metadata from external system */
            metadata?: Record<string, unknown>;
        }

        export namespace Item {
            /** Product kind - subscription or one-time */
            export const Kind = {
                Subscription: "subscription",
                OneTime: "one_time",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
            /** Billing interval for subscriptions */
            export const Interval = {
                Day: "day",
                Week: "week",
                Month: "month",
                Year: "year",
            } as const;
            export type Interval = (typeof Interval)[keyof typeof Interval];
        }
    }
}
