// This file was auto-generated by Fern from our API Definition.
export var UpdateProductRequest;
(function (UpdateProductRequest) {
    /** Fulfillment type for the product. */
    UpdateProductRequest.FulfillmentType = {
        None: "none",
        Digital: "digital",
        Physical: "physical",
    };
    /** How billing dates are calculated. same_day: Bill on same day as start. day_of_month: Bill on specific day (1-31). last_day: Bill on last day of month. */
    UpdateProductRequest.BillingAnchorRule = {
        SameDay: "same_day",
        DayOfMonth: "day_of_month",
        LastDay: "last_day",
    };
    /** When first payment is collected. immediate: Charge on start. next_anchor: Charge on first scheduled date. prorate: Prorate until first date. */
    UpdateProductRequest.FirstChargeBehavior = {
        Immediate: "immediate",
        NextAnchor: "next_anchor",
        Prorate: "prorate",
    };
    /** How subscription ends. until_canceled: Runs forever. fixed_payments: Ends after N billing cycles. */
    UpdateProductRequest.EndBehavior = {
        UntilCanceled: "until_canceled",
        FixedPayments: "fixed_payments",
    };
})(UpdateProductRequest || (UpdateProductRequest = {}));
//# sourceMappingURL=UpdateProductRequest.js.map