// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         threadId: "threadId"
 *     }
 */
export interface CommsMessagesListRequest {
    /** Thread UUID */
    threadId: string;
    /** Maximum number of results (1-100) */
    limit?: number;
    /** Number of results to skip */
    offset?: number | null;
}
