// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         customerId: "customerId",
 *         benefitKey: "benefitKey"
 *     }
 */
export interface CustomersEntitlementsCheckRequest {
    /** Customer UUID */
    customerId: string;
    /** Benefit key to check */
    benefitKey: string;
}
