// This file was auto-generated by Fern from our API Definition.
import { normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as RevKeen from "../../../index.js";
/**
 * Setup Intents save payment methods WITHOUT charging. Use them to collect card details for future use (subscriptions, saved cards) or to verify cards with 3DS/SCA before storing.
 *
 * **Required Scopes:**
 * - `setup_intents:read` - List and retrieve setup intents
 * - `setup_intents:write` - Create, confirm, cancel setup intents
 *
 * **MCP Tools:** Available via `customers_*` tools
 */
export class SetupIntentsClient {
    constructor(options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }
    /**
     * Returns a list of setup intents. The setup intents are returned sorted by creation date, with the most recent first.
     *
     * @param {RevKeen.ListSetupIntentsRequest} request
     * @param {SetupIntentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.ForbiddenError}
     *
     * @example
     *     await client.setupIntents.list()
     */
    list(request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }
    async __list(request = {}, requestOptions) {
        const { customer_id: customerId, status, limit, starting_after: startingAfter, ending_before: endingBefore, } = request;
        const _queryParams = {
            customer_id: customerId,
            status: status != null ? status : undefined,
            limit,
            starting_after: startingAfter,
            ending_before: endingBefore,
        };
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, "setup-intents"),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 403:
                    throw new RevKeen.ForbiddenError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/setup-intents");
    }
    /**
     * Creates a new setup intent for saving a payment method without charging.
     *
     * **Use Cases:**
     * - Save a card for future subscription payments
     * - Pre-authorize a payment method with 3DS/SCA verification
     * - Collect payment details for later use (off-session payments)
     *
     * The setup intent is created in `requires_payment_method` status. Use the `client_secret` to complete the setup flow on the client side.
     *
     * @param {RevKeen.CreateSetupIntentRequest} request
     * @param {SetupIntentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.ForbiddenError}
     *
     * @example
     *     await client.setupIntents.create()
     */
    create(request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }
    async __create(request = {}, requestOptions) {
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, "setup-intents"),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 403:
                    throw new RevKeen.ForbiddenError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/setup-intents");
    }
    /**
     * Retrieves a setup intent by ID. You can use either the internal UUID or the public ID (seti_xxx format).
     *
     * @param {RevKeen.RetrieveSetupIntentsRequest} request
     * @param {SetupIntentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.ForbiddenError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.setupIntents.retrieve({
     *         id: "seti_1a2b3c4d5e6f"
     *     })
     */
    retrieve(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }
    async __retrieve(request, requestOptions) {
        const { id } = request;
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, `setup-intents/${core.url.encodePathParam(id)}`),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 403:
                    throw new RevKeen.ForbiddenError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/setup-intents/{id}");
    }
    /**
     * Updates a setup intent that has not yet been confirmed or canceled.
     *
     * You can update:
     * - `customer_id` - The customer to attach the payment method to
     * - `payment_method_types` - Allowed payment method types
     * - `description` - Merchant description
     * - `metadata` - Custom metadata
     *
     * @param {RevKeen.UpdateSetupIntentRequest} request
     * @param {SetupIntentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.ForbiddenError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.setupIntents.update({
     *         id: "seti_1a2b3c4d5e6f"
     *     })
     */
    update(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }
    async __update(request, requestOptions) {
        const { id, ..._body } = request;
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, `setup-intents/${core.url.encodePathParam(id)}`),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 403:
                    throw new RevKeen.ForbiddenError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/setup-intents/{id}");
    }
    /**
     * Confirms a setup intent and saves the payment method.
     *
     * **3DS/SCA Flow:**
     * If the payment method requires authentication, the setup intent will transition to `requires_action` status with a `next_action` containing the redirect URL. After the customer completes authentication, the setup intent will automatically transition to `succeeded`.
     *
     * **Direct Confirmation:**
     * If no authentication is required, the setup intent will immediately transition to `succeeded` and the payment method will be saved to the customer.
     *
     * @param {RevKeen.ConfirmSetupIntentRequest} request
     * @param {SetupIntentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.ForbiddenError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.setupIntents.confirm({
     *         id: "seti_1a2b3c4d5e6f"
     *     })
     */
    confirm(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__confirm(request, requestOptions));
    }
    async __confirm(request, requestOptions) {
        const { id, ..._body } = request;
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, `setup-intents/${core.url.encodePathParam(id)}/confirm`),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 403:
                    throw new RevKeen.ForbiddenError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/setup-intents/{id}/confirm");
    }
    /**
     * Cancels a setup intent that has not yet succeeded.
     *
     * Once canceled, the setup intent cannot be confirmed. A new setup intent must be created to save a payment method.
     *
     * @param {RevKeen.CancelSetupIntentRequest} request
     * @param {SetupIntentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.ForbiddenError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.setupIntents.cancel({
     *         id: "seti_1a2b3c4d5e6f"
     *     })
     */
    cancel(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__cancel(request, requestOptions));
    }
    async __cancel(request, requestOptions) {
        const { id, ..._body } = request;
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, `setup-intents/${core.url.encodePathParam(id)}/cancel`),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 403:
                    throw new RevKeen.ForbiddenError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/setup-intents/{id}/cancel");
    }
}
//# sourceMappingURL=Client.js.map