// This file was auto-generated by Fern from our API Definition.
export var CreateDiscountInput;
(function (CreateDiscountInput) {
    /** Type of discount */
    CreateDiscountInput.DiscountType = {
        Percentage: "percentage",
        FixedAmount: "fixed_amount",
    };
    /** Which products the discount applies to */
    CreateDiscountInput.AppliesTo = {
        All: "all",
        SpecificProducts: "specific_products",
    };
    /** Scope of where discount can be applied */
    CreateDiscountInput.Scope = {
        EntireOrder: "entire_order",
        SpecificProducts: "specific_products",
        SubscriptionOnly: "subscription_only",
        OneTimeOnly: "one_time_only",
    };
    /** How the discount applies to recurring payments */
    CreateDiscountInput.RecurringType = {
        Once: "once",
        Forever: "forever",
        Repeating: "repeating",
    };
})(CreateDiscountInput || (CreateDiscountInput = {}));
//# sourceMappingURL=CreateDiscountInput.js.map