// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../../../../index.js";

/**
 * @example
 *     {
 *         limit: 20
 *     }
 */
export interface DiscountsListRequest {
    /** Filter by active status */
    is_active?: RevKeen.DiscountsListRequestIsActive;
    /** Filter by archived status */
    is_archived?: RevKeen.DiscountsListRequestIsArchived;
    /** Number of results to return (1-100) */
    limit?: number;
    /** Number of results to skip */
    offset?: number | null;
}
