// This file was auto-generated by Fern from our API Definition.
export var UpdateDiscountInput;
(function (UpdateDiscountInput) {
    UpdateDiscountInput.AppliesTo = {
        All: "all",
        SpecificProducts: "specific_products",
    };
    UpdateDiscountInput.Scope = {
        EntireOrder: "entire_order",
        SpecificProducts: "specific_products",
        SubscriptionOnly: "subscription_only",
        OneTimeOnly: "one_time_only",
    };
    UpdateDiscountInput.RecurringType = {
        Once: "once",
        Forever: "forever",
        Repeating: "repeating",
    };
})(UpdateDiscountInput || (UpdateDiscountInput = {}));
//# sourceMappingURL=UpdateDiscountInput.js.map