// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface VoidsRetrieveRequest {
    /** Void public ID (void_xxx) or UUID */
    id: string;
}
