// This file was auto-generated by Fern from our API Definition.
export var SyncStateUpdateResponse;
(function (SyncStateUpdateResponse) {
    let Data;
    (function (Data) {
        Data.LastSyncStatus = {
            Idle: "idle",
            Syncing: "syncing",
            Success: "success",
            Error: "error",
        };
    })(Data = SyncStateUpdateResponse.Data || (SyncStateUpdateResponse.Data = {}));
})(SyncStateUpdateResponse || (SyncStateUpdateResponse = {}));
//# sourceMappingURL=SyncStateUpdateResponse.js.map