// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as RevKeen from "../../../index.js";

export declare namespace UserInvitationsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class UserInvitationsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<UserInvitationsClient.Options>;

    constructor(options: UserInvitationsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List pending invitations for the client. Requires admin role.
     *
     * @param {UserInvitationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.ForbiddenError}
     *
     * @example
     *     await client.userInvitations.listInvitations()
     */
    public listInvitations(
        requestOptions?: UserInvitationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.GetUserInvitationsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listInvitations(requestOptions));
    }

    private async __listInvitations(
        requestOptions?: UserInvitationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.GetUserInvitationsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                "user-invitations",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.GetUserInvitationsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new RevKeen.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/user-invitations");
    }

    /**
     * Invite a new user to join the client. Requires admin role.
     *
     * @param {RevKeen.PostUserInvitationsRequest} request
     * @param {UserInvitationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.ForbiddenError}
     *
     * @example
     *     await client.userInvitations.inviteUser({
     *         email: "email",
     *         role: "admin"
     *     })
     */
    public inviteUser(
        request: RevKeen.PostUserInvitationsRequest,
        requestOptions?: UserInvitationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.PostUserInvitationsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__inviteUser(request, requestOptions));
    }

    private async __inviteUser(
        request: RevKeen.PostUserInvitationsRequest,
        requestOptions?: UserInvitationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.PostUserInvitationsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                "user-invitations",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.PostUserInvitationsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new RevKeen.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/user-invitations");
    }

    /**
     * Resend invitation email. Requires admin role.
     *
     * @param {RevKeen.PostUserInvitationsIdResendRequest} request
     * @param {UserInvitationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.ForbiddenError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.userInvitations.resendInvitation({
     *         id: "id"
     *     })
     */
    public resendInvitation(
        request: RevKeen.PostUserInvitationsIdResendRequest,
        requestOptions?: UserInvitationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.PostUserInvitationsIdResendResponse> {
        return core.HttpResponsePromise.fromPromise(this.__resendInvitation(request, requestOptions));
    }

    private async __resendInvitation(
        request: RevKeen.PostUserInvitationsIdResendRequest,
        requestOptions?: UserInvitationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.PostUserInvitationsIdResendResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `user-invitations/${core.url.encodePathParam(id)}/resend`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.PostUserInvitationsIdResendResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new RevKeen.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/user-invitations/{id}/resend",
        );
    }

    /**
     * Cancel/revoke invitation. Requires admin role.
     *
     * @param {RevKeen.DeleteUserInvitationsIdRequest} request
     * @param {UserInvitationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.ForbiddenError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.userInvitations.cancelInvitation({
     *         id: "id"
     *     })
     */
    public cancelInvitation(
        request: RevKeen.DeleteUserInvitationsIdRequest,
        requestOptions?: UserInvitationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.DeleteUserInvitationsIdResponse> {
        return core.HttpResponsePromise.fromPromise(this.__cancelInvitation(request, requestOptions));
    }

    private async __cancelInvitation(
        request: RevKeen.DeleteUserInvitationsIdRequest,
        requestOptions?: UserInvitationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.DeleteUserInvitationsIdResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `user-invitations/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.DeleteUserInvitationsIdResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new RevKeen.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/user-invitations/{id}");
    }

    /**
     * Accept invitation and complete signup. No auth required (uses invitation token).
     *
     * @param {RevKeen.PostUserInvitationsAcceptRequest} request
     * @param {UserInvitationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.userInvitations.acceptInvitation({
     *         invitationToken: "invitationToken",
     *         password: "password"
     *     })
     */
    public acceptInvitation(
        request: RevKeen.PostUserInvitationsAcceptRequest,
        requestOptions?: UserInvitationsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.PostUserInvitationsAcceptResponse> {
        return core.HttpResponsePromise.fromPromise(this.__acceptInvitation(request, requestOptions));
    }

    private async __acceptInvitation(
        request: RevKeen.PostUserInvitationsAcceptRequest,
        requestOptions?: UserInvitationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.PostUserInvitationsAcceptResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                "user-invitations/accept",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.PostUserInvitationsAcceptResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/user-invitations/accept");
    }
}
