// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as RevKeen from "../../../index.js";

export declare namespace EventsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Event objects represent something that happened in your account — a payment succeeded, an invoice was created, a subscription was canceled. Events are the source of truth for webhook delivery. Use them to debug webhook issues, replay missed events, or build an audit trail.
 *
 * **Required Scopes:**
 * - `events:read` - List and retrieve events
 * - `events:write` - Resend webhook events
 */
export class EventsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EventsClient.Options>;

    constructor(options: EventsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns a list of events with optional filters. Events are returned in reverse chronological order.
     *
     * @param {RevKeen.EventsListRequest} request
     * @param {EventsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     *
     * @example
     *     await client.events.list({
     *         type: "invoice.paid",
     *         types: "invoice.paid,payment.succeeded"
     *     })
     */
    public list(
        request: RevKeen.EventsListRequest = {},
        requestOptions?: EventsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.EventListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: RevKeen.EventsListRequest = {},
        requestOptions?: EventsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.EventListResponse>> {
        const {
            type: type_,
            types,
            customer_id: customerId,
            invoice_id: invoiceId,
            subscription_id: subscriptionId,
            order_id: orderId,
            created_gte: createdGte,
            created_lte: createdLte,
            limit,
            starting_after: startingAfter,
            ending_before: endingBefore,
        } = request;
        const _queryParams: Record<string, unknown> = {
            type: type_,
            types,
            customer_id: customerId,
            invoice_id: invoiceId,
            subscription_id: subscriptionId,
            order_id: orderId,
            created_gte: createdGte,
            created_lte: createdLte,
            limit,
            starting_after: startingAfter,
            ending_before: endingBefore,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                "events",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.EventListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/events");
    }

    /**
     * Retrieves the details of an event by its ID.
     *
     * @param {RevKeen.EventsRetrieveRequest} request
     * @param {EventsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.events.retrieve({
     *         id: "id"
     *     })
     */
    public retrieve(
        request: RevKeen.EventsRetrieveRequest,
        requestOptions?: EventsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.Event> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }

    private async __retrieve(
        request: RevKeen.EventsRetrieveRequest,
        requestOptions?: EventsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.Event>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `events/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.Event, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/events/{id}");
    }

    /**
     * Queues the event to be resent to all configured webhook endpoints.
     *
     * @param {RevKeen.EventsResendRequest} request
     * @param {EventsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.events.resend({
     *         id: "id"
     *     })
     */
    public resend(
        request: RevKeen.EventsResendRequest,
        requestOptions?: EventsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.ResendWebhookResponse> {
        return core.HttpResponsePromise.fromPromise(this.__resend(request, requestOptions));
    }

    private async __resend(
        request: RevKeen.EventsResendRequest,
        requestOptions?: EventsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.ResendWebhookResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `events/${core.url.encodePathParam(id)}/resend`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.ResendWebhookResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/events/{id}/resend");
    }

    /**
     * Creates a simulated test event that triggers webhook delivery to configured endpoints. Useful for testing webhook integrations.
     *
     * @param {RevKeen.CreateTestEventRequest} request
     * @param {EventsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     *
     * @example
     *     await client.events.createTest({
     *         type: "checkout.session.completed"
     *     })
     */
    public createTest(
        request: RevKeen.CreateTestEventRequest,
        requestOptions?: EventsClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.TestEventResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createTest(request, requestOptions));
    }

    private async __createTest(
        request: RevKeen.CreateTestEventRequest,
        requestOptions?: EventsClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.TestEventResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                "events/test",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.TestEventResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/events/test");
    }
}
