// This file was auto-generated by Fern from our API Definition.
export var WebhookEndpointsListResponse;
(function (WebhookEndpointsListResponse) {
    let Data;
    (function (Data) {
        let Item;
        (function (Item) {
            Item.Status = {
                Enabled: "enabled",
                Disabled: "disabled",
            };
            Item.CircuitBreakerState = {
                Closed: "closed",
                Open: "open",
                HalfOpen: "half_open",
            };
        })(Item = Data.Item || (Data.Item = {}));
    })(Data = WebhookEndpointsListResponse.Data || (WebhookEndpointsListResponse.Data = {}));
})(WebhookEndpointsListResponse || (WebhookEndpointsListResponse = {}));
//# sourceMappingURL=WebhookEndpointsListResponse.js.map