// This file was auto-generated by Fern from our API Definition.
/** Filter by status */
export const AnalyticsCheckoutWinbackListRequestStatus = {
    Identified: "identified",
    Contacted: "contacted",
    Converted: "converted",
    Declined: "declined",
    Expired: "expired",
};
//# sourceMappingURL=AnalyticsCheckoutWinbackListRequestStatus.js.map