// This file was auto-generated by Fern from our API Definition.

export interface AnalyticsCustomersGetLtvResponse {
    customers: AnalyticsCustomersGetLtvResponse.Customers.Item[];
    avgLtv: number;
    medianLtv: number;
}

export namespace AnalyticsCustomersGetLtvResponse {
    export type Customers = Customers.Item[];

    export namespace Customers {
        export interface Item {
            customerId: string;
            customerName: string;
            ltv: number;
            totalRevenue: number;
            avgOrderValue: number;
            orderCount: number;
        }
    }
}
