// This file was auto-generated by Fern from our API Definition.
/** Filter by opportunity type */
export const AnalyticsCheckoutWinbackListRequestType = {
    CancelledSubscription: "cancelled_subscription",
    RepeatAbandoner: "repeat_abandoner",
    LapsedCustomer: "lapsed_customer",
};
//# sourceMappingURL=AnalyticsCheckoutWinbackListRequestType.js.map