// This file was auto-generated by Fern from our API Definition.
export var AnalyticsCheckoutWinbackListResponse;
(function (AnalyticsCheckoutWinbackListResponse) {
    let Opportunities;
    (function (Opportunities) {
        let Item;
        (function (Item) {
            Item.OpportunityType = {
                CancelledSubscription: "cancelled_subscription",
                RepeatAbandoner: "repeat_abandoner",
                LapsedCustomer: "lapsed_customer",
            };
            Item.Status = {
                Identified: "identified",
                Contacted: "contacted",
                Converted: "converted",
                Declined: "declined",
                Expired: "expired",
            };
        })(Item = Opportunities.Item || (Opportunities.Item = {}));
    })(Opportunities = AnalyticsCheckoutWinbackListResponse.Opportunities || (AnalyticsCheckoutWinbackListResponse.Opportunities = {}));
})(AnalyticsCheckoutWinbackListResponse || (AnalyticsCheckoutWinbackListResponse = {}));
//# sourceMappingURL=AnalyticsCheckoutWinbackListResponse.js.map