// This file was auto-generated by Fern from our API Definition.
/** Group results by time period */
export const FinanceGetIncomeRequestGroupBy = {
    Day: "day",
    Week: "week",
    Month: "month",
};
//# sourceMappingURL=FinanceGetIncomeRequestGroupBy.js.map