// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         payment_id: "660e8400-e29b-41d4-a716-446655440000"
 *     }
 */
export interface CreateRefundInput {
    /** The ID of the payment to refund */
    payment_id: string;
    /** Amount to refund in cents. If not provided, refunds the full remaining amount. */
    amount_minor?: number;
    /** Reason for the refund */
    reason?: CreateRefundInput.Reason;
    /** Additional details about the refund reason */
    reason_details?: string;
}

export namespace CreateRefundInput {
    /** Reason for the refund */
    export const Reason = {
        CustomerRequest: "customer_request",
        Duplicate: "duplicate",
        Fraudulent: "fraudulent",
        ProductNotReceived: "product_not_received",
        ProductUnacceptable: "product_unacceptable",
        SubscriptionCanceled: "subscription_canceled",
        Other: "other",
    } as const;
    export type Reason = (typeof Reason)[keyof typeof Reason];
}
