// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface RefundsRetrieveRequest {
    /** Refund public ID (ref_xxx) or UUID */
    id: string;
}
