// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as RevKeen from "../../../index.js";

export declare namespace PaymentLinksClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Create shareable payment links for invoices, subscriptions, or custom amounts. Customers complete payment on a hosted page.
 *
 * **Required Scopes:**
 * - `payment_links:read` - List and retrieve payment links
 * - `payment_links:write` - Create and update payment links
 */
export class PaymentLinksClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PaymentLinksClient.Options>;

    constructor(options: PaymentLinksClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List payment links for the authenticated merchant with pagination and filters
     *
     * @param {RevKeen.ListPaymentLinksRequest} request
     * @param {PaymentLinksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     *
     * @example
     *     await client.paymentLinks.listPaymentLinks()
     */
    public listPaymentLinks(
        request: RevKeen.ListPaymentLinksRequest = {},
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.ListPaymentLinksResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listPaymentLinks(request, requestOptions));
    }

    private async __listPaymentLinks(
        request: RevKeen.ListPaymentLinksRequest = {},
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.ListPaymentLinksResponse>> {
        const { limit, offset, status, mode, search } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
            status: status != null ? status : undefined,
            mode: mode != null ? mode : undefined,
            search,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                "payment-links",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.ListPaymentLinksResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/payment-links");
    }

    /**
     * Create a new payment link for invoices, subscriptions, or custom amounts
     *
     * @param {RevKeen.CreatePaymentLinkRequest} request
     * @param {PaymentLinksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.ConflictError}
     *
     * @example
     *     await client.paymentLinks.createPaymentLink()
     */
    public createPaymentLink(
        request: RevKeen.CreatePaymentLinkRequest = {},
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.CreatePaymentLinkResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createPaymentLink(request, requestOptions));
    }

    private async __createPaymentLink(
        request: RevKeen.CreatePaymentLinkRequest = {},
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.CreatePaymentLinkResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                "payment-links",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.CreatePaymentLinkResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new RevKeen.ConflictError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/payment-links");
    }

    /**
     * Retrieve a payment link by its UUID or public_id
     *
     * @param {RevKeen.GetPaymentLinkRequest} request
     * @param {PaymentLinksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.paymentLinks.getPaymentLink({
     *         id: "id"
     *     })
     */
    public getPaymentLink(
        request: RevKeen.GetPaymentLinkRequest,
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.GetPaymentLinkResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getPaymentLink(request, requestOptions));
    }

    private async __getPaymentLink(
        request: RevKeen.GetPaymentLinkRequest,
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.GetPaymentLinkResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `payment-links/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.GetPaymentLinkResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/payment-links/{id}");
    }

    /**
     * Mark a payment link as expired, preventing further use
     *
     * @param {RevKeen.ExpirePaymentLinkRequest} request
     * @param {PaymentLinksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.paymentLinks.expirePaymentLink({
     *         id: "id"
     *     })
     */
    public expirePaymentLink(
        request: RevKeen.ExpirePaymentLinkRequest,
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.ExpirePaymentLinkResponse> {
        return core.HttpResponsePromise.fromPromise(this.__expirePaymentLink(request, requestOptions));
    }

    private async __expirePaymentLink(
        request: RevKeen.ExpirePaymentLinkRequest,
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.ExpirePaymentLinkResponse>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `payment-links/${core.url.encodePathParam(id)}/expire`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.ExpirePaymentLinkResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/payment-links/{id}/expire");
    }

    /**
     * Change the status of a payment link. Active links accept payments, inactive links are temporarily disabled, and archived links are permanently disabled and cannot be reactivated.
     *
     * @param {RevKeen.UpdatePaymentLinkStatusRequest} request
     * @param {PaymentLinksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.paymentLinks.updatePaymentLinkStatus({
     *         id: "id",
     *         status: "active"
     *     })
     */
    public updatePaymentLinkStatus(
        request: RevKeen.UpdatePaymentLinkStatusRequest,
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.UpdatePaymentLinkStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updatePaymentLinkStatus(request, requestOptions));
    }

    private async __updatePaymentLinkStatus(
        request: RevKeen.UpdatePaymentLinkStatusRequest,
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.UpdatePaymentLinkStatusResponse>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `payment-links/${core.url.encodePathParam(id)}/status`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.UpdatePaymentLinkStatusResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/payment-links/{id}/status");
    }

    /**
     * Temporarily disable a payment link. It can be reactivated later.
     *
     * @param {RevKeen.DeactivatePaymentLinkRequest} request
     * @param {PaymentLinksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.paymentLinks.deactivatePaymentLink({
     *         id: "id"
     *     })
     */
    public deactivatePaymentLink(
        request: RevKeen.DeactivatePaymentLinkRequest,
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.DeactivatePaymentLinkResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deactivatePaymentLink(request, requestOptions));
    }

    private async __deactivatePaymentLink(
        request: RevKeen.DeactivatePaymentLinkRequest,
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.DeactivatePaymentLinkResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `payment-links/${core.url.encodePathParam(id)}/deactivate`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as RevKeen.DeactivatePaymentLinkResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/payment-links/{id}/deactivate",
        );
    }

    /**
     * Enable a payment link to accept payments. Cannot be used on archived links.
     *
     * @param {RevKeen.ActivatePaymentLinkRequest} request
     * @param {PaymentLinksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.paymentLinks.activatePaymentLink({
     *         id: "id"
     *     })
     */
    public activatePaymentLink(
        request: RevKeen.ActivatePaymentLinkRequest,
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.ActivatePaymentLinkResponse> {
        return core.HttpResponsePromise.fromPromise(this.__activatePaymentLink(request, requestOptions));
    }

    private async __activatePaymentLink(
        request: RevKeen.ActivatePaymentLinkRequest,
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.ActivatePaymentLinkResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `payment-links/${core.url.encodePathParam(id)}/activate`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.ActivatePaymentLinkResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/payment-links/{id}/activate");
    }

    /**
     * Permanently disable a payment link. This action cannot be undone.
     *
     * @param {RevKeen.ArchivePaymentLinkRequest} request
     * @param {PaymentLinksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.paymentLinks.archivePaymentLink({
     *         id: "id"
     *     })
     */
    public archivePaymentLink(
        request: RevKeen.ArchivePaymentLinkRequest,
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): core.HttpResponsePromise<RevKeen.ArchivePaymentLinkResponse> {
        return core.HttpResponsePromise.fromPromise(this.__archivePaymentLink(request, requestOptions));
    }

    private async __archivePaymentLink(
        request: RevKeen.ArchivePaymentLinkRequest,
        requestOptions?: PaymentLinksClient.RequestOptions,
    ): Promise<core.WithRawResponse<RevKeen.ArchivePaymentLinkResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RevKeenEnvironment.Default,
                `payment-links/${core.url.encodePathParam(id)}/archive`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as RevKeen.ArchivePaymentLinkResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/payment-links/{id}/archive");
    }
}
