// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "email",
 *         role: "admin"
 *     }
 */
export interface PostUserInvitationsRequest {
    email: string;
    role: PostUserInvitationsRequest.Role;
    merchantId?: string;
}

export namespace PostUserInvitationsRequest {
    export const Role = {
        Admin: "admin",
        Member: "member",
        Viewer: "viewer",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
