// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         invitationToken: "invitationToken",
 *         password: "password"
 *     }
 */
export interface PostUserInvitationsAcceptRequest {
    invitationToken: string;
    password: string;
    name?: string;
}
