// This file was auto-generated by Fern from our API Definition.

export const IntegrationsGetStatusRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
    Terminal: "terminal",
} as const;
export type IntegrationsGetStatusRequestProvider =
    (typeof IntegrationsGetStatusRequestProvider)[keyof typeof IntegrationsGetStatusRequestProvider];
