// This file was auto-generated by Fern from our API Definition.
export const IntegrationsDeactivateRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
};
//# sourceMappingURL=IntegrationsDeactivateRequestProvider.js.map