// This file was auto-generated by Fern from our API Definition.
export const IntegrationsGetProductMappingsRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
};
//# sourceMappingURL=IntegrationsGetProductMappingsRequestProvider.js.map