// This file was auto-generated by Fern from our API Definition.

export const IntegrationsGetPaymentMethodsRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
    Terminal: "terminal",
} as const;
export type IntegrationsGetPaymentMethodsRequestProvider =
    (typeof IntegrationsGetPaymentMethodsRequestProvider)[keyof typeof IntegrationsGetPaymentMethodsRequestProvider];
