// This file was auto-generated by Fern from our API Definition.

export interface IntegrationsGetBillableItemsResponse {
    success: boolean;
    data: IntegrationsGetBillableItemsResponse.Data.Item[];
}

export namespace IntegrationsGetBillableItemsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            id: Item.Id;
            name: string;
            type?: string | null;
            charge_type?: string | null;
            price?: number | null;
            source: Item.Source;
        }

        export namespace Item {
            export type Id = string | number;
            export const Source = {
                Invoice: "invoice",
            } as const;
            export type Source = (typeof Source)[keyof typeof Source];
        }
    }
}
