// This file was auto-generated by Fern from our API Definition.
export var IntegrationsGetStatusResponse;
(function (IntegrationsGetStatusResponse) {
    let Data;
    (function (Data) {
        Data.Provider = {
            Practicehub: "practicehub",
            Wodify: "wodify",
            Terminal: "terminal",
        };
        Data.Status = {
            Connected: "connected",
            Error: "error",
            Syncing: "syncing",
            Idle: "idle",
        };
    })(Data = IntegrationsGetStatusResponse.Data || (IntegrationsGetStatusResponse.Data = {}));
})(IntegrationsGetStatusResponse || (IntegrationsGetStatusResponse = {}));
//# sourceMappingURL=IntegrationsGetStatusResponse.js.map