// This file was auto-generated by Fern from our API Definition.

export interface IntegrationsGetStatusResponse {
    data: IntegrationsGetStatusResponse.Data | null;
}

export namespace IntegrationsGetStatusResponse {
    export interface Data {
        id: string;
        provider: Data.Provider;
        isActive: boolean;
        syncEnabled?: boolean;
        status: Data.Status | null;
        lastSyncAt: string | null;
        lastSyncError: string | null;
        syncHealth?: Data.SyncHealth;
        providerState?: Data.ProviderState | null;
        syncInterval?: Data.SyncInterval;
        configuration?: Record<string, unknown>;
        createdAt: string;
        updatedAt: string;
    }

    export namespace Data {
        export const Provider = {
            Practicehub: "practicehub",
            Wodify: "wodify",
            Terminal: "terminal",
        } as const;
        export type Provider = (typeof Provider)[keyof typeof Provider];
        export const Status = {
            Connected: "connected",
            Error: "error",
            Syncing: "syncing",
            Idle: "idle",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
        export const SyncHealth = {
            Healthy: "healthy",
            Degraded: "degraded",
            Paused: "paused",
        } as const;
        export type SyncHealth = (typeof SyncHealth)[keyof typeof SyncHealth];

        export interface ProviderState {
            consecutiveErrors: number;
            lastErrorAt: string | null;
            lastSyncAt: string | null;
            mode: string;
        }

        export interface SyncInterval {
            hasRepeatableJob: boolean;
            intervalMs?: number;
            nextRun?: string;
        }
    }
}
