// This file was auto-generated by Fern from our API Definition.

export const IntegrationsGetProductMappingsRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
    Terminal: "terminal",
} as const;
export type IntegrationsGetProductMappingsRequestProvider =
    (typeof IntegrationsGetProductMappingsRequestProvider)[keyof typeof IntegrationsGetProductMappingsRequestProvider];
