// This file was auto-generated by Fern from our API Definition.
export const IntegrationsDeleteProductMappingRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
};
//# sourceMappingURL=IntegrationsDeleteProductMappingRequestProvider.js.map