// This file was auto-generated by Fern from our API Definition.

export const IntegrationsDeactivateRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
} as const;
export type IntegrationsDeactivateRequestProvider =
    (typeof IntegrationsDeactivateRequestProvider)[keyof typeof IntegrationsDeactivateRequestProvider];
