// This file was auto-generated by Fern from our API Definition.
export const IntegrationsSyncLogsRequestJobType = {
    Scheduled: "scheduled",
    Manual: "manual",
    SingleRetry: "single_retry",
    BatchRetry: "batch_retry",
};
//# sourceMappingURL=IntegrationsSyncLogsRequestJobType.js.map