// This file was auto-generated by Fern from our API Definition.
export const IntegrationsActivateRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
    Terminal: "terminal",
};
//# sourceMappingURL=IntegrationsActivateRequestProvider.js.map