// This file was auto-generated by Fern from our API Definition.

export interface IntegrationsGetPaymentMethodsResponse {
    success: boolean;
    data: IntegrationsGetPaymentMethodsResponse.Data.Item[];
}

export namespace IntegrationsGetPaymentMethodsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            id: number;
            name: string;
            active: boolean;
            sort_order: number;
        }
    }
}
