// This file was auto-generated by Fern from our API Definition.

export const IntegrationsInvoiceLookbackRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
    Terminal: "terminal",
} as const;
export type IntegrationsInvoiceLookbackRequestProvider =
    (typeof IntegrationsInvoiceLookbackRequestProvider)[keyof typeof IntegrationsInvoiceLookbackRequestProvider];
