// This file was auto-generated by Fern from our API Definition.
export var IntegrationsListResponse;
(function (IntegrationsListResponse) {
    let Data;
    (function (Data) {
        let Item;
        (function (Item) {
            Item.Provider = {
                Practicehub: "practicehub",
                Wodify: "wodify",
                Terminal: "terminal",
            };
            Item.Status = {
                Connected: "connected",
                Error: "error",
                Syncing: "syncing",
                Idle: "idle",
            };
            Item.SyncHealth = {
                Healthy: "healthy",
                Degraded: "degraded",
                Paused: "paused",
            };
        })(Item = Data.Item || (Data.Item = {}));
    })(Data = IntegrationsListResponse.Data || (IntegrationsListResponse.Data = {}));
})(IntegrationsListResponse || (IntegrationsListResponse = {}));
//# sourceMappingURL=IntegrationsListResponse.js.map