// This file was auto-generated by Fern from our API Definition.
export const IntegrationsInvoiceLookbackRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
};
//# sourceMappingURL=IntegrationsInvoiceLookbackRequestProvider.js.map