// This file was auto-generated by Fern from our API Definition.
export const IntegrationsPutProductMappingsRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
    Terminal: "terminal",
};
//# sourceMappingURL=IntegrationsPutProductMappingsRequestProvider.js.map