// This file was auto-generated by Fern from our API Definition.

export interface IntegrationsSyncStatesResponse {
    success: boolean;
    data: IntegrationsSyncStatesResponse.Data.Item[];
}

export namespace IntegrationsSyncStatesResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            resourceType: string;
            lastSyncAt: string | null;
            lastSyncStatus: string | null;
            itemsProcessed: number | null;
            lastSyncError: string | null;
            cursor: string | null;
        }
    }
}
