// This file was auto-generated by Fern from our API Definition.

export interface IntegrationsGetUnmappedAttemptsResponse {
    success: boolean;
    data: IntegrationsGetUnmappedAttemptsResponse.Data.Item[];
    totalCount: number;
}

export namespace IntegrationsGetUnmappedAttemptsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            externalPackageId: string;
            externalPackageName: string | null;
            count: number;
            lastSeenAt: string | null;
        }
    }
}
