// This file was auto-generated by Fern from our API Definition.
export const IntegrationsTestRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
    Terminal: "terminal",
};
//# sourceMappingURL=IntegrationsTestRequestProvider.js.map