// This file was auto-generated by Fern from our API Definition.

export const IntegrationsAutoSendInvoicesRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
    Terminal: "terminal",
} as const;
export type IntegrationsAutoSendInvoicesRequestProvider =
    (typeof IntegrationsAutoSendInvoicesRequestProvider)[keyof typeof IntegrationsAutoSendInvoicesRequestProvider];
