// This file was auto-generated by Fern from our API Definition.

export const IntegrationsSyncLogByIdRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
} as const;
export type IntegrationsSyncLogByIdRequestProvider =
    (typeof IntegrationsSyncLogByIdRequestProvider)[keyof typeof IntegrationsSyncLogByIdRequestProvider];
