// This file was auto-generated by Fern from our API Definition.
export const IntegrationsSuggestMappingsRequestProvider = {
    Practicehub: "practicehub",
    Wodify: "wodify",
    Terminal: "terminal",
};
//# sourceMappingURL=IntegrationsSuggestMappingsRequestProvider.js.map