// This file was auto-generated by Fern from our API Definition.

export interface IntegrationsGetStatusResponse {
    data: IntegrationsGetStatusResponse.Data | null;
}

export namespace IntegrationsGetStatusResponse {
    export interface Data {
        id: string;
        provider: Data.Provider;
        isActive: boolean;
        status: Data.Status | null;
        lastSyncAt: string | null;
        lastSyncError: string | null;
        syncInterval?: Data.SyncInterval;
        createdAt: string;
        updatedAt: string;
    }

    export namespace Data {
        export const Provider = {
            Practicehub: "practicehub",
            Wodify: "wodify",
            Terminal: "terminal",
        } as const;
        export type Provider = (typeof Provider)[keyof typeof Provider];
        export const Status = {
            Connected: "connected",
            Error: "error",
            Syncing: "syncing",
            Idle: "idle",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];

        export interface SyncInterval {
            hasRepeatableJob: boolean;
            intervalMs?: number;
            nextRun?: string;
        }
    }
}
