// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../../../../index.js";

/**
 * @example
 *     {
 *         provider: "practicehub",
 *         mappings: [{
 *                 externalId: "externalId",
 *                 internalId: "internalId"
 *             }]
 *     }
 */
export interface IntegrationsPutProductMappingsRequest {
    provider: RevKeen.IntegrationsPutProductMappingsRequestProvider;
    mappings: IntegrationsPutProductMappingsRequest.Mappings.Item[];
}

export namespace IntegrationsPutProductMappingsRequest {
    export type Mappings = Mappings.Item[];

    export namespace Mappings {
        export interface Item {
            externalId: string;
            internalId: string;
            metadata?: Item.Metadata;
        }

        export namespace Item {
            export interface Metadata {
                name?: string;
                type?: string;
                charge_type?: string;
            }
        }
    }
}
