// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../../../../index.js";

/**
 * @example
 *     {
 *         provider: "practicehub",
 *         externalItems: [{
 *                 id: "id",
 *                 name: "name",
 *                 source: "package"
 *             }]
 *     }
 */
export interface IntegrationsSuggestMappingsRequest {
    provider: RevKeen.IntegrationsSuggestMappingsRequestProvider;
    externalItems: IntegrationsSuggestMappingsRequest.ExternalItems.Item[];
}

export namespace IntegrationsSuggestMappingsRequest {
    export type ExternalItems = ExternalItems.Item[];

    export namespace ExternalItems {
        export interface Item {
            id: string;
            name: string;
            type?: string | null;
            charge_type?: string | null;
            price?: number | null;
            source: Item.Source;
        }

        export namespace Item {
            export const Source = {
                Package: "package",
                Invoice: "invoice",
                Unmapped: "unmapped",
            } as const;
            export type Source = (typeof Source)[keyof typeof Source];
        }
    }
}
