// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface VoidTerminalPaymentRequest {
    /** Terminal payment attempt ID of the original sale */
    id: string;
    /** Reason for the void */
    reason?: string;
}
