// This file was auto-generated by Fern from our API Definition.
/** Filter by status */
export const PaymentsListRequestStatus = {
    Pending: "pending",
    Authorized: "authorized",
    Captured: "captured",
    Succeeded: "succeeded",
    Failed: "failed",
    Voided: "voided",
    Refunded: "refunded",
    PartiallyRefunded: "partially_refunded",
};
//# sourceMappingURL=PaymentsListRequestStatus.js.map