// This file was auto-generated by Fern from our API Definition.
/** Filter by archived status */
export const DiscountsListRequestIsArchived = {
    True: "true",
    False: "false",
};
//# sourceMappingURL=DiscountsListRequestIsArchived.js.map