// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ActivatePaymentLinkRequest {
    /** Payment link UUID or public_id */
    id: string;
}
