// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListPaymentLinksRequest {
    limit?: number;
    offset?: number | null;
    status?: RevKeen.ListPaymentLinksRequestStatus;
    mode?: RevKeen.ListPaymentLinksRequestMode;
    search?: string;
}
