// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../../../index.js";

export interface CreditNotesInvoiceEligibilityResponse {
    data: RevKeen.CreditNoteEligibilityResponse;
}
