// This file was auto-generated by Fern from our API Definition.

import type * as RevKeen from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateSubscriptionScheduleRequest {
    /** Schedule ID (sub_sched_xxx or UUID) */
    id: string;
    /** Replace all phases */
    phases?: RevKeen.SchedulePhase[];
    /** What happens when all phases complete */
    end_behavior?: UpdateSubscriptionScheduleRequest.EndBehavior;
    /** Proration behavior when updating phases */
    proration_behavior?: UpdateSubscriptionScheduleRequest.ProrationBehavior;
    /** Custom metadata */
    metadata?: Record<string, unknown>;
}

export namespace UpdateSubscriptionScheduleRequest {
    /** What happens when all phases complete */
    export const EndBehavior = {
        Cancel: "cancel",
        Release: "release",
    } as const;
    export type EndBehavior = (typeof EndBehavior)[keyof typeof EndBehavior];
    /** Proration behavior when updating phases */
    export const ProrationBehavior = {
        CreateProrations: "create_prorations",
        None: "none",
        AlwaysInvoice: "always_invoice",
    } as const;
    export type ProrationBehavior = (typeof ProrationBehavior)[keyof typeof ProrationBehavior];
}
