// This file was auto-generated by Fern from our API Definition.
import { normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as RevKeen from "../../../index.js";
/**
 * Issue formal accounting corrections for paid or partially paid invoices. A credit note is the accounting document; a refund is the money movement. They are often created together.
 *
 * **Required Scopes:**
 * - `credit_notes:read` - List and retrieve credit notes
 * - `credit_notes:write` - Create and void credit notes
 */
export class CreditNotesClient {
    constructor(options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }
    /**
     * Retrieve a paginated list of credit notes with optional filters. Results are ordered by creation date (newest first).
     *
     * @param {RevKeen.CreditNotesListRequest} request
     * @param {CreditNotesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.creditNotes.list({
     *         created_after: "2024-01-01T00:00:00Z",
     *         created_before: "2024-12-31T23:59:59Z",
     *         limit: 20
     *     })
     */
    list(request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }
    async __list(request = {}, requestOptions) {
        const { status, invoice_id: invoiceId, customer_id: customerId, credit_method: creditMethod, created_after: createdAfter, created_before: createdBefore, limit, offset, } = request;
        const _queryParams = {
            status: status != null ? status : undefined,
            invoice_id: invoiceId,
            customer_id: customerId,
            credit_method: creditMethod != null ? creditMethod : undefined,
            created_after: createdAfter,
            created_before: createdBefore,
            limit,
            offset,
        };
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, "credit_notes"),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/credit_notes");
    }
    /**
     * Issue a credit note for a paid or partially paid invoice. The credit can be applied via refund to payment method, customer balance, or marked as external.
     *
     * @param {RevKeen.CreateCreditNoteInput} request
     * @param {CreditNotesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.ConflictError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.creditNotes.create({
     *         invoice_id: "660e8400-e29b-41d4-a716-446655440000",
     *         amount_minor: 5000
     *     })
     */
    create(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }
    async __create(request, requestOptions) {
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, "credit_notes"),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 409:
                    throw new RevKeen.ConflictError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/credit_notes");
    }
    /**
     * Retrieve a single credit note by its UUID.
     *
     * @param {RevKeen.CreditNotesRetrieveRequest} request
     * @param {CreditNotesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.creditNotes.retrieve({
     *         id: "id"
     *     })
     */
    retrieve(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }
    async __retrieve(request, requestOptions) {
        const { id } = request;
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, `credit_notes/${core.url.encodePathParam(id)}`),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/credit_notes/{id}");
    }
    /**
     * Void a credit note that has been issued but not yet fully applied. This is an accounting void — it reverses the credit without creating a new financial transaction.
     *
     * @param {RevKeen.CreditNotesVoidRequest} request
     * @param {CreditNotesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.BadRequestError}
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     * @throws {@link RevKeen.InternalServerError}
     *
     * @example
     *     await client.creditNotes.void({
     *         id: "id"
     *     })
     */
    void(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__void(request, requestOptions));
    }
    async __void(request, requestOptions) {
        const { id } = request;
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, `credit_notes/${core.url.encodePathParam(id)}/void`),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RevKeen.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new RevKeen.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/credit_notes/{id}/void");
    }
    /**
     * Returns per-payment breakdown of available reversal operations across all gateways. Use this before creating a credit note to understand what reversal methods are available.
     *
     * @param {RevKeen.CreditNotesInvoiceEligibilityRequest} request
     * @param {CreditNotesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.creditNotes.invoiceEligibility({
     *         invoice_id: "invoice_id"
     *     })
     */
    invoiceEligibility(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__invoiceEligibility(request, requestOptions));
    }
    async __invoiceEligibility(request, requestOptions) {
        const { invoice_id: invoiceId } = request;
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, `credit_notes/invoice/${core.url.encodePathParam(invoiceId)}/eligibility`),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body,
                rawResponse: _response.rawResponse,
            };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/credit_notes/invoice/{invoice_id}/eligibility");
    }
    /**
     * Returns available reversal operations for a specific payment transaction, including terminal-specific options and NMI fallback paths. For terminal (card-present) transactions, pass `customer_present=true` to see terminal-native operations.
     *
     * @param {RevKeen.CreditNotesTransactionReversalEligibilityRequest} request
     * @param {CreditNotesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RevKeen.UnauthorizedError}
     * @throws {@link RevKeen.NotFoundError}
     *
     * @example
     *     await client.creditNotes.transactionReversalEligibility({
     *         transaction_id: "transaction_id"
     *     })
     */
    transactionReversalEligibility(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__transactionReversalEligibility(request, requestOptions));
    }
    async __transactionReversalEligibility(request, requestOptions) {
        const { transaction_id: transactionId, customer_present: customerPresent } = request;
        const _queryParams = {
            customer_present: customerPresent,
        };
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.RevKeenEnvironment.Default, `credit_notes/transaction/${core.url.encodePathParam(transactionId)}/reversal-eligibility`),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body,
                rawResponse: _response.rawResponse,
            };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new RevKeen.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new RevKeen.NotFoundError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.RevKeenError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/credit_notes/transaction/{transaction_id}/reversal-eligibility");
    }
}
//# sourceMappingURL=Client.js.map