// This file was auto-generated by Fern from our API Definition.

/** Filter by tax type */
export const GetTaxRatesRequestTaxType = {
    Vat: "vat",
    SalesTax: "sales_tax",
    Gst: "gst",
    Other: "other",
} as const;
export type GetTaxRatesRequestTaxType = (typeof GetTaxRatesRequestTaxType)[keyof typeof GetTaxRatesRequestTaxType];
