// This file was auto-generated by Fern from our API Definition.
export var CreateImportRequest;
(function (CreateImportRequest) {
    /** The type of resource to import. */
    CreateImportRequest.ResourceType = {
        Customers: "customers",
        Products: "products",
        Invoices: "invoices",
    };
    /** Behavior when a duplicate record is found. skip: ignore the row. update: merge new data. error: fail the row. */
    CreateImportRequest.OnDuplicate = {
        Skip: "skip",
        Update: "update",
        Error: "error",
    };
})(CreateImportRequest || (CreateImportRequest = {}));
//# sourceMappingURL=CreateImportRequest.js.map