// This file was auto-generated by Fern from our API Definition.

export interface CustomersEntitlementsCheckResponse {
    data: CustomersEntitlementsCheckResponse.Data;
}

export namespace CustomersEntitlementsCheckResponse {
    export interface Data {
        benefitKey: string;
        hasAccess: boolean;
        accessLevel: Data.AccessLevel;
        status: Data.Status | null;
        benefit: Data.Benefit | null;
        reason: string | null;
    }

    export namespace Data {
        export const AccessLevel = {
            Full: "full",
            Partial: "partial",
            None: "none",
        } as const;
        export type AccessLevel = (typeof AccessLevel)[keyof typeof AccessLevel];
        export const Status = {
            Active: "active",
            Trialing: "trialing",
            Grace: "grace",
            PastDue: "past_due",
            Restricted: "restricted",
            Suspended: "suspended",
            Canceled: "canceled",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];

        export interface Benefit {
            id: string;
            name: string;
            description: string | null;
            benefitType: string;
            benefitKey: string;
            category: string | null;
            iconUrl: string | null;
            displayOrder: string | null;
            isActive: boolean | null;
            defaultValue?: unknown;
            config?: unknown;
        }
    }
}
