// This file was auto-generated by Fern from our API Definition.
export var CustomersEntitlementsListResponse;
(function (CustomersEntitlementsListResponse) {
    let Data;
    (function (Data) {
        let Item;
        (function (Item) {
            Item.Status = {
                Active: "active",
                Trialing: "trialing",
                Grace: "grace",
                PastDue: "past_due",
                Restricted: "restricted",
                Suspended: "suspended",
                Canceled: "canceled",
            };
            Item.AccessLevel = {
                Full: "full",
                Partial: "partial",
                None: "none",
            };
        })(Item = Data.Item || (Data.Item = {}));
    })(Data = CustomersEntitlementsListResponse.Data || (CustomersEntitlementsListResponse.Data = {}));
})(CustomersEntitlementsListResponse || (CustomersEntitlementsListResponse = {}));
//# sourceMappingURL=CustomersEntitlementsListResponse.js.map