// This file was auto-generated by Fern from our API Definition.
export var CustomersEntitlementsRevokeByKeyResponse;
(function (CustomersEntitlementsRevokeByKeyResponse) {
    let Data;
    (function (Data) {
        Data.Status = {
            Active: "active",
            Trialing: "trialing",
            Grace: "grace",
            PastDue: "past_due",
            Restricted: "restricted",
            Suspended: "suspended",
            Canceled: "canceled",
        };
        Data.AccessLevel = {
            Full: "full",
            Partial: "partial",
            None: "none",
        };
    })(Data = CustomersEntitlementsRevokeByKeyResponse.Data || (CustomersEntitlementsRevokeByKeyResponse.Data = {}));
})(CustomersEntitlementsRevokeByKeyResponse || (CustomersEntitlementsRevokeByKeyResponse = {}));
//# sourceMappingURL=CustomersEntitlementsRevokeByKeyResponse.js.map